// Code generated by ent, DO NOT EDIT.

package fielddefinitiontranslation

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// FieldDefinitionID applies equality check predicate on the "field_definition_id" field. It's identical to FieldDefinitionIDEQ.
func FieldDefinitionID(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldFieldDefinitionID, v))
}

// LanguageCode applies equality check predicate on the "language_code" field. It's identical to LanguageCodeEQ.
func LanguageCode(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDescription, v))
}

// Placeholder applies equality check predicate on the "placeholder" field. It's identical to PlaceholderEQ.
func Placeholder(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldPlaceholder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldDeletedBy))
}

// FieldDefinitionIDEQ applies the EQ predicate on the "field_definition_id" field.
func FieldDefinitionIDEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDNEQ applies the NEQ predicate on the "field_definition_id" field.
func FieldDefinitionIDNEQ(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDIn applies the In predicate on the "field_definition_id" field.
func FieldDefinitionIDIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldFieldDefinitionID, vs...))
}

// FieldDefinitionIDNotIn applies the NotIn predicate on the "field_definition_id" field.
func FieldDefinitionIDNotIn(vs ...uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldFieldDefinitionID, vs...))
}

// FieldDefinitionIDGT applies the GT predicate on the "field_definition_id" field.
func FieldDefinitionIDGT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDGTE applies the GTE predicate on the "field_definition_id" field.
func FieldDefinitionIDGTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDLT applies the LT predicate on the "field_definition_id" field.
func FieldDefinitionIDLT(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDLTE applies the LTE predicate on the "field_definition_id" field.
func FieldDefinitionIDLTE(v uint32) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldFieldDefinitionID, v))
}

// FieldDefinitionIDIsNil applies the IsNil predicate on the "field_definition_id" field.
func FieldDefinitionIDIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldFieldDefinitionID))
}

// FieldDefinitionIDNotNil applies the NotNil predicate on the "field_definition_id" field.
func FieldDefinitionIDNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldFieldDefinitionID))
}

// LanguageCodeEQ applies the EQ predicate on the "language_code" field.
func LanguageCodeEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// LanguageCodeNEQ applies the NEQ predicate on the "language_code" field.
func LanguageCodeNEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldLanguageCode, v))
}

// LanguageCodeIn applies the In predicate on the "language_code" field.
func LanguageCodeIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldLanguageCode, vs...))
}

// LanguageCodeNotIn applies the NotIn predicate on the "language_code" field.
func LanguageCodeNotIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldLanguageCode, vs...))
}

// LanguageCodeGT applies the GT predicate on the "language_code" field.
func LanguageCodeGT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldLanguageCode, v))
}

// LanguageCodeGTE applies the GTE predicate on the "language_code" field.
func LanguageCodeGTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldLanguageCode, v))
}

// LanguageCodeLT applies the LT predicate on the "language_code" field.
func LanguageCodeLT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldLanguageCode, v))
}

// LanguageCodeLTE applies the LTE predicate on the "language_code" field.
func LanguageCodeLTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldLanguageCode, v))
}

// LanguageCodeContains applies the Contains predicate on the "language_code" field.
func LanguageCodeContains(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContains(FieldLanguageCode, v))
}

// LanguageCodeHasPrefix applies the HasPrefix predicate on the "language_code" field.
func LanguageCodeHasPrefix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasPrefix(FieldLanguageCode, v))
}

// LanguageCodeHasSuffix applies the HasSuffix predicate on the "language_code" field.
func LanguageCodeHasSuffix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasSuffix(FieldLanguageCode, v))
}

// LanguageCodeIsNil applies the IsNil predicate on the "language_code" field.
func LanguageCodeIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldLanguageCode))
}

// LanguageCodeNotNil applies the NotNil predicate on the "language_code" field.
func LanguageCodeNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldLanguageCode))
}

// LanguageCodeEqualFold applies the EqualFold predicate on the "language_code" field.
func LanguageCodeEqualFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEqualFold(FieldLanguageCode, v))
}

// LanguageCodeContainsFold applies the ContainsFold predicate on the "language_code" field.
func LanguageCodeContainsFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContainsFold(FieldLanguageCode, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContainsFold(FieldLabel, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContainsFold(FieldDescription, v))
}

// PlaceholderEQ applies the EQ predicate on the "placeholder" field.
func PlaceholderEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEQ(FieldPlaceholder, v))
}

// PlaceholderNEQ applies the NEQ predicate on the "placeholder" field.
func PlaceholderNEQ(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNEQ(FieldPlaceholder, v))
}

// PlaceholderIn applies the In predicate on the "placeholder" field.
func PlaceholderIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIn(FieldPlaceholder, vs...))
}

// PlaceholderNotIn applies the NotIn predicate on the "placeholder" field.
func PlaceholderNotIn(vs ...string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotIn(FieldPlaceholder, vs...))
}

// PlaceholderGT applies the GT predicate on the "placeholder" field.
func PlaceholderGT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGT(FieldPlaceholder, v))
}

// PlaceholderGTE applies the GTE predicate on the "placeholder" field.
func PlaceholderGTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldGTE(FieldPlaceholder, v))
}

// PlaceholderLT applies the LT predicate on the "placeholder" field.
func PlaceholderLT(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLT(FieldPlaceholder, v))
}

// PlaceholderLTE applies the LTE predicate on the "placeholder" field.
func PlaceholderLTE(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldLTE(FieldPlaceholder, v))
}

// PlaceholderContains applies the Contains predicate on the "placeholder" field.
func PlaceholderContains(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContains(FieldPlaceholder, v))
}

// PlaceholderHasPrefix applies the HasPrefix predicate on the "placeholder" field.
func PlaceholderHasPrefix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasPrefix(FieldPlaceholder, v))
}

// PlaceholderHasSuffix applies the HasSuffix predicate on the "placeholder" field.
func PlaceholderHasSuffix(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldHasSuffix(FieldPlaceholder, v))
}

// PlaceholderIsNil applies the IsNil predicate on the "placeholder" field.
func PlaceholderIsNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldIsNull(FieldPlaceholder))
}

// PlaceholderNotNil applies the NotNil predicate on the "placeholder" field.
func PlaceholderNotNil() predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldNotNull(FieldPlaceholder))
}

// PlaceholderEqualFold applies the EqualFold predicate on the "placeholder" field.
func PlaceholderEqualFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldEqualFold(FieldPlaceholder, v))
}

// PlaceholderContainsFold applies the ContainsFold predicate on the "placeholder" field.
func PlaceholderContainsFold(v string) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.FieldContainsFold(FieldPlaceholder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldDefinitionTranslation) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldDefinitionTranslation) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldDefinitionTranslation) predicate.FieldDefinitionTranslation {
	return predicate.FieldDefinitionTranslation(sql.NotPredicates(p))
}
