// Code generated by ent, DO NOT EDIT.

package tagtranslation

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldTagID, v))
}

// LanguageCode applies equality check predicate on the "language_code" field. It's identical to LanguageCodeEQ.
func LanguageCode(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldSlug, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDescription, v))
}

// CoverImage applies equality check predicate on the "cover_image" field. It's identical to CoverImageEQ.
func CoverImage(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCoverImage, v))
}

// Template applies equality check predicate on the "template" field. It's identical to TemplateEQ.
func Template(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldTemplate, v))
}

// FullPath applies equality check predicate on the "full_path" field. It's identical to FullPathEQ.
func FullPath(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldFullPath, v))
}

// CanonicalURL applies equality check predicate on the "canonical_url" field. It's identical to CanonicalURLEQ.
func CanonicalURL(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCanonicalURL, v))
}

// MetaKeywords applies equality check predicate on the "meta_keywords" field. It's identical to MetaKeywordsEQ.
func MetaKeywords(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldMetaKeywords, v))
}

// MetaDescription applies equality check predicate on the "meta_description" field. It's identical to MetaDescriptionEQ.
func MetaDescription(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldDeletedBy))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldTagID, vs...))
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldTagID, v))
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldTagID, v))
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldTagID, v))
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v uint32) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldTagID, v))
}

// TagIDIsNil applies the IsNil predicate on the "tag_id" field.
func TagIDIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldTagID))
}

// TagIDNotNil applies the NotNil predicate on the "tag_id" field.
func TagIDNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldTagID))
}

// LanguageCodeEQ applies the EQ predicate on the "language_code" field.
func LanguageCodeEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// LanguageCodeNEQ applies the NEQ predicate on the "language_code" field.
func LanguageCodeNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldLanguageCode, v))
}

// LanguageCodeIn applies the In predicate on the "language_code" field.
func LanguageCodeIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldLanguageCode, vs...))
}

// LanguageCodeNotIn applies the NotIn predicate on the "language_code" field.
func LanguageCodeNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldLanguageCode, vs...))
}

// LanguageCodeGT applies the GT predicate on the "language_code" field.
func LanguageCodeGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldLanguageCode, v))
}

// LanguageCodeGTE applies the GTE predicate on the "language_code" field.
func LanguageCodeGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldLanguageCode, v))
}

// LanguageCodeLT applies the LT predicate on the "language_code" field.
func LanguageCodeLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldLanguageCode, v))
}

// LanguageCodeLTE applies the LTE predicate on the "language_code" field.
func LanguageCodeLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldLanguageCode, v))
}

// LanguageCodeContains applies the Contains predicate on the "language_code" field.
func LanguageCodeContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldLanguageCode, v))
}

// LanguageCodeHasPrefix applies the HasPrefix predicate on the "language_code" field.
func LanguageCodeHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldLanguageCode, v))
}

// LanguageCodeHasSuffix applies the HasSuffix predicate on the "language_code" field.
func LanguageCodeHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldLanguageCode, v))
}

// LanguageCodeIsNil applies the IsNil predicate on the "language_code" field.
func LanguageCodeIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldLanguageCode))
}

// LanguageCodeNotNil applies the NotNil predicate on the "language_code" field.
func LanguageCodeNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldLanguageCode))
}

// LanguageCodeEqualFold applies the EqualFold predicate on the "language_code" field.
func LanguageCodeEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldLanguageCode, v))
}

// LanguageCodeContainsFold applies the ContainsFold predicate on the "language_code" field.
func LanguageCodeContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldLanguageCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldSlug, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldDescription, v))
}

// CoverImageEQ applies the EQ predicate on the "cover_image" field.
func CoverImageEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageNEQ applies the NEQ predicate on the "cover_image" field.
func CoverImageNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldCoverImage, v))
}

// CoverImageIn applies the In predicate on the "cover_image" field.
func CoverImageIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldCoverImage, vs...))
}

// CoverImageNotIn applies the NotIn predicate on the "cover_image" field.
func CoverImageNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldCoverImage, vs...))
}

// CoverImageGT applies the GT predicate on the "cover_image" field.
func CoverImageGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldCoverImage, v))
}

// CoverImageGTE applies the GTE predicate on the "cover_image" field.
func CoverImageGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldCoverImage, v))
}

// CoverImageLT applies the LT predicate on the "cover_image" field.
func CoverImageLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldCoverImage, v))
}

// CoverImageLTE applies the LTE predicate on the "cover_image" field.
func CoverImageLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldCoverImage, v))
}

// CoverImageContains applies the Contains predicate on the "cover_image" field.
func CoverImageContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldCoverImage, v))
}

// CoverImageHasPrefix applies the HasPrefix predicate on the "cover_image" field.
func CoverImageHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldCoverImage, v))
}

// CoverImageHasSuffix applies the HasSuffix predicate on the "cover_image" field.
func CoverImageHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldCoverImage, v))
}

// CoverImageIsNil applies the IsNil predicate on the "cover_image" field.
func CoverImageIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldCoverImage))
}

// CoverImageNotNil applies the NotNil predicate on the "cover_image" field.
func CoverImageNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldCoverImage))
}

// CoverImageEqualFold applies the EqualFold predicate on the "cover_image" field.
func CoverImageEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldCoverImage, v))
}

// CoverImageContainsFold applies the ContainsFold predicate on the "cover_image" field.
func CoverImageContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldCoverImage, v))
}

// TemplateEQ applies the EQ predicate on the "template" field.
func TemplateEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldTemplate, v))
}

// TemplateNEQ applies the NEQ predicate on the "template" field.
func TemplateNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldTemplate, v))
}

// TemplateIn applies the In predicate on the "template" field.
func TemplateIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldTemplate, vs...))
}

// TemplateNotIn applies the NotIn predicate on the "template" field.
func TemplateNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldTemplate, vs...))
}

// TemplateGT applies the GT predicate on the "template" field.
func TemplateGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldTemplate, v))
}

// TemplateGTE applies the GTE predicate on the "template" field.
func TemplateGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldTemplate, v))
}

// TemplateLT applies the LT predicate on the "template" field.
func TemplateLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldTemplate, v))
}

// TemplateLTE applies the LTE predicate on the "template" field.
func TemplateLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldTemplate, v))
}

// TemplateContains applies the Contains predicate on the "template" field.
func TemplateContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldTemplate, v))
}

// TemplateHasPrefix applies the HasPrefix predicate on the "template" field.
func TemplateHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldTemplate, v))
}

// TemplateHasSuffix applies the HasSuffix predicate on the "template" field.
func TemplateHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldTemplate, v))
}

// TemplateIsNil applies the IsNil predicate on the "template" field.
func TemplateIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldTemplate))
}

// TemplateNotNil applies the NotNil predicate on the "template" field.
func TemplateNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldTemplate))
}

// TemplateEqualFold applies the EqualFold predicate on the "template" field.
func TemplateEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldTemplate, v))
}

// TemplateContainsFold applies the ContainsFold predicate on the "template" field.
func TemplateContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldTemplate, v))
}

// FullPathEQ applies the EQ predicate on the "full_path" field.
func FullPathEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldFullPath, v))
}

// FullPathNEQ applies the NEQ predicate on the "full_path" field.
func FullPathNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldFullPath, v))
}

// FullPathIn applies the In predicate on the "full_path" field.
func FullPathIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldFullPath, vs...))
}

// FullPathNotIn applies the NotIn predicate on the "full_path" field.
func FullPathNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldFullPath, vs...))
}

// FullPathGT applies the GT predicate on the "full_path" field.
func FullPathGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldFullPath, v))
}

// FullPathGTE applies the GTE predicate on the "full_path" field.
func FullPathGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldFullPath, v))
}

// FullPathLT applies the LT predicate on the "full_path" field.
func FullPathLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldFullPath, v))
}

// FullPathLTE applies the LTE predicate on the "full_path" field.
func FullPathLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldFullPath, v))
}

// FullPathContains applies the Contains predicate on the "full_path" field.
func FullPathContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldFullPath, v))
}

// FullPathHasPrefix applies the HasPrefix predicate on the "full_path" field.
func FullPathHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldFullPath, v))
}

// FullPathHasSuffix applies the HasSuffix predicate on the "full_path" field.
func FullPathHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldFullPath, v))
}

// FullPathIsNil applies the IsNil predicate on the "full_path" field.
func FullPathIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldFullPath))
}

// FullPathNotNil applies the NotNil predicate on the "full_path" field.
func FullPathNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldFullPath))
}

// FullPathEqualFold applies the EqualFold predicate on the "full_path" field.
func FullPathEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldFullPath, v))
}

// FullPathContainsFold applies the ContainsFold predicate on the "full_path" field.
func FullPathContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldFullPath, v))
}

// CanonicalURLEQ applies the EQ predicate on the "canonical_url" field.
func CanonicalURLEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldCanonicalURL, v))
}

// CanonicalURLNEQ applies the NEQ predicate on the "canonical_url" field.
func CanonicalURLNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldCanonicalURL, v))
}

// CanonicalURLIn applies the In predicate on the "canonical_url" field.
func CanonicalURLIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldCanonicalURL, vs...))
}

// CanonicalURLNotIn applies the NotIn predicate on the "canonical_url" field.
func CanonicalURLNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldCanonicalURL, vs...))
}

// CanonicalURLGT applies the GT predicate on the "canonical_url" field.
func CanonicalURLGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldCanonicalURL, v))
}

// CanonicalURLGTE applies the GTE predicate on the "canonical_url" field.
func CanonicalURLGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldCanonicalURL, v))
}

// CanonicalURLLT applies the LT predicate on the "canonical_url" field.
func CanonicalURLLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldCanonicalURL, v))
}

// CanonicalURLLTE applies the LTE predicate on the "canonical_url" field.
func CanonicalURLLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldCanonicalURL, v))
}

// CanonicalURLContains applies the Contains predicate on the "canonical_url" field.
func CanonicalURLContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldCanonicalURL, v))
}

// CanonicalURLHasPrefix applies the HasPrefix predicate on the "canonical_url" field.
func CanonicalURLHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldCanonicalURL, v))
}

// CanonicalURLHasSuffix applies the HasSuffix predicate on the "canonical_url" field.
func CanonicalURLHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldCanonicalURL, v))
}

// CanonicalURLIsNil applies the IsNil predicate on the "canonical_url" field.
func CanonicalURLIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldCanonicalURL))
}

// CanonicalURLNotNil applies the NotNil predicate on the "canonical_url" field.
func CanonicalURLNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldCanonicalURL))
}

// CanonicalURLEqualFold applies the EqualFold predicate on the "canonical_url" field.
func CanonicalURLEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldCanonicalURL, v))
}

// CanonicalURLContainsFold applies the ContainsFold predicate on the "canonical_url" field.
func CanonicalURLContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldCanonicalURL, v))
}

// MetaKeywordsEQ applies the EQ predicate on the "meta_keywords" field.
func MetaKeywordsEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldMetaKeywords, v))
}

// MetaKeywordsNEQ applies the NEQ predicate on the "meta_keywords" field.
func MetaKeywordsNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldMetaKeywords, v))
}

// MetaKeywordsIn applies the In predicate on the "meta_keywords" field.
func MetaKeywordsIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldMetaKeywords, vs...))
}

// MetaKeywordsNotIn applies the NotIn predicate on the "meta_keywords" field.
func MetaKeywordsNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldMetaKeywords, vs...))
}

// MetaKeywordsGT applies the GT predicate on the "meta_keywords" field.
func MetaKeywordsGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldMetaKeywords, v))
}

// MetaKeywordsGTE applies the GTE predicate on the "meta_keywords" field.
func MetaKeywordsGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldMetaKeywords, v))
}

// MetaKeywordsLT applies the LT predicate on the "meta_keywords" field.
func MetaKeywordsLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldMetaKeywords, v))
}

// MetaKeywordsLTE applies the LTE predicate on the "meta_keywords" field.
func MetaKeywordsLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldMetaKeywords, v))
}

// MetaKeywordsContains applies the Contains predicate on the "meta_keywords" field.
func MetaKeywordsContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldMetaKeywords, v))
}

// MetaKeywordsHasPrefix applies the HasPrefix predicate on the "meta_keywords" field.
func MetaKeywordsHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldMetaKeywords, v))
}

// MetaKeywordsHasSuffix applies the HasSuffix predicate on the "meta_keywords" field.
func MetaKeywordsHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldMetaKeywords, v))
}

// MetaKeywordsIsNil applies the IsNil predicate on the "meta_keywords" field.
func MetaKeywordsIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldMetaKeywords))
}

// MetaKeywordsNotNil applies the NotNil predicate on the "meta_keywords" field.
func MetaKeywordsNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldMetaKeywords))
}

// MetaKeywordsEqualFold applies the EqualFold predicate on the "meta_keywords" field.
func MetaKeywordsEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldMetaKeywords, v))
}

// MetaKeywordsContainsFold applies the ContainsFold predicate on the "meta_keywords" field.
func MetaKeywordsContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldMetaKeywords, v))
}

// MetaDescriptionEQ applies the EQ predicate on the "meta_description" field.
func MetaDescriptionEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// MetaDescriptionNEQ applies the NEQ predicate on the "meta_description" field.
func MetaDescriptionNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldMetaDescription, v))
}

// MetaDescriptionIn applies the In predicate on the "meta_description" field.
func MetaDescriptionIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldMetaDescription, vs...))
}

// MetaDescriptionNotIn applies the NotIn predicate on the "meta_description" field.
func MetaDescriptionNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldMetaDescription, vs...))
}

// MetaDescriptionGT applies the GT predicate on the "meta_description" field.
func MetaDescriptionGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldMetaDescription, v))
}

// MetaDescriptionGTE applies the GTE predicate on the "meta_description" field.
func MetaDescriptionGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldMetaDescription, v))
}

// MetaDescriptionLT applies the LT predicate on the "meta_description" field.
func MetaDescriptionLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldMetaDescription, v))
}

// MetaDescriptionLTE applies the LTE predicate on the "meta_description" field.
func MetaDescriptionLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldMetaDescription, v))
}

// MetaDescriptionContains applies the Contains predicate on the "meta_description" field.
func MetaDescriptionContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldMetaDescription, v))
}

// MetaDescriptionHasPrefix applies the HasPrefix predicate on the "meta_description" field.
func MetaDescriptionHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldMetaDescription, v))
}

// MetaDescriptionHasSuffix applies the HasSuffix predicate on the "meta_description" field.
func MetaDescriptionHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldMetaDescription, v))
}

// MetaDescriptionIsNil applies the IsNil predicate on the "meta_description" field.
func MetaDescriptionIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldMetaDescription))
}

// MetaDescriptionNotNil applies the NotNil predicate on the "meta_description" field.
func MetaDescriptionNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldMetaDescription))
}

// MetaDescriptionEqualFold applies the EqualFold predicate on the "meta_description" field.
func MetaDescriptionEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldMetaDescription, v))
}

// MetaDescriptionContainsFold applies the ContainsFold predicate on the "meta_description" field.
func MetaDescriptionContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldMetaDescription, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleIsNil applies the IsNil predicate on the "seo_title" field.
func SeoTitleIsNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldIsNull(FieldSeoTitle))
}

// SeoTitleNotNil applies the NotNil predicate on the "seo_title" field.
func SeoTitleNotNil() predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldNotNull(FieldSeoTitle))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.TagTranslation {
	return predicate.TagTranslation(sql.FieldContainsFold(FieldSeoTitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TagTranslation) predicate.TagTranslation {
	return predicate.TagTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TagTranslation) predicate.TagTranslation {
	return predicate.TagTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TagTranslation) predicate.TagTranslation {
	return predicate.TagTranslation(sql.NotPredicates(p))
}
