import {
  Delete,
  Save,
  ProgressBarRound,
  Template,
  Layers,
  DataBin,
  Moon,
  Sun,
  TextIndentLess,
  TextIndentMore,
  DataBase,
  GroupObjects,
  UserAvatar,
  Code,
  Development,
  Help,
  TableAlias,
  TemperatureCelsius,
  AreaCustom,
  Map,
  Draggable,
  RadioButtonChecked,
  ContainerRegistry,
  Script,
  Airplay,
  Edit,
  CloseOutline,
  CheckmarkOutline,
  TextFill,
  QuadrantPlot,
  LicenseMaintenance,
  Course,
  ChartRing,
  OpenPanelRight,
  OpenPanelLeft,
  ContainerSoftware
} from '@vicons/carbon'

import {
  ClearOutlined,
  CloudDownloadOutlined,
  CloudUploadOutlined,
  HomeOutlined,
  LogoutOutlined,
  PictureOutlined,
  DashboardOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  ApiOutlined
} from '@vicons/antd'

import {
  CubeOutline,
  FolderOpenOutline,
  CopyOutline,
  RefreshOutline,
  SearchOutline,
  TrashOutline,
  BookmarkOutline
} from '@vicons/ionicons5'

const icons = {
  delete: Delete,
  previewOpen: EyeOutlined,
  previewClose: EyeInvisibleOutlined,
  clear: ClearOutlined,
  download: CloudDownloadOutlined,
  upload: CloudUploadOutlined,
  save: Save,
  home: HomeOutlined,
  logout: LogoutOutlined,
  template: Template,
  picture: PictureOutlined,
  expandLeft: OpenPanelLeft,
  expandRight: OpenPanelRight,
  components: ContainerRegistry,
  layers: Layers,
  textStyle: TextFill,
  InternalData: DataBin,
  sun: Sun,
  moon: Moon,
  textIndentLess: TextIndentLess,
  textIndentMore: TextIndentMore,
  data: DataBase,
  cube: CubeOutline,
  dashboard: DashboardOutlined,
  user: UserAvatar,
  api: ApiOutlined,
  code: Code,
  group: GroupObjects,
  development: Development,
  help: Help,
  progress: ProgressBarRound,
  table: TableAlias,
  thermometer: TemperatureCelsius,
  custom: AreaCustom,
  map: Map,
  other: Draggable,
  button: RadioButtonChecked,
  script: Script,
  preview: Airplay,
  edit: Edit,
  close: CloseOutline,
  check: CheckmarkOutline,
  attr: QuadrantPlot,
  license: LicenseMaintenance,
  course: Course,
  intro: ChartRing,
  container: ContainerSoftware,
  search: SearchOutline,
  open: FolderOpenOutline,
  copy: CopyOutline,
  trash: TrashOutline,
  refresh: RefreshOutline,
  bookmark: BookmarkOutline
}

export default icons
