// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-cms/app/app/service/internal/data"
	"go-wind-cms/app/app/service/internal/server"
	"go-wind-cms/app/app/service/internal/service"
	"go-wind-cms/pkg/middleware/auth"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/registry/etcd"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(context)
	authenticationServiceClient := data.NewAuthenticationServiceClient(context, discovery)
	clientType := data.NewClientType()
	accessTokenChecker := auth.NewTokenChecker(context, authenticationServiceClient, clientType)
	engine := data.NewAuthorizer()
	v := server.NewRestMiddleware(context, accessTokenChecker, engine)
	authenticationService := service.NewAuthenticationService(context, authenticationServiceClient)
	postServiceClient := data.NewPostServiceClient(context, discovery)
	postService := service.NewPostService(context, postServiceClient)
	categoryServiceClient := data.NewCategoryServiceClient(context, discovery)
	categoryService := service.NewCategoryService(context, categoryServiceClient)
	commentServiceClient := data.NewCommentServiceClient(context, discovery)
	commentService := service.NewCommentService(context, commentServiceClient)
	tagServiceClient := data.NewTagServiceClient(context, discovery)
	tagService := service.NewTagService(context, tagServiceClient)
	pageServiceClient := data.NewPageServiceClient(context, discovery)
	pageService := service.NewPageService(context, pageServiceClient)
	httpServer := server.NewRestServer(context, v, authenticationService, postService, categoryService, commentService, tagService, pageService)
	grpcMiddlewares := server.NewGrpcMiddleware(context)
	grpcServer, err := server.NewGrpcServer(context, grpcMiddlewares)
	if err != nil {
		return nil, nil, err
	}
	sseServer := server.NewSseServer(context)
	app := newApp(context, httpServer, grpcServer, sseServer)
	return app, func() {
	}, nil
}
