// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/contentmodel"
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContentModelUpdate is the builder for updating ContentModel entities.
type ContentModelUpdate struct {
	config
	hooks     []Hook
	mutation  *ContentModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ContentModelUpdate builder.
func (_u *ContentModelUpdate) Where(ps ...predicate.ContentModel) *ContentModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContentModelUpdate) SetUpdatedAt(v time.Time) *ContentModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableUpdatedAt(v *time.Time) *ContentModelUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ContentModelUpdate) ClearUpdatedAt() *ContentModelUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ContentModelUpdate) SetDeletedAt(v time.Time) *ContentModelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableDeletedAt(v *time.Time) *ContentModelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ContentModelUpdate) ClearDeletedAt() *ContentModelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ContentModelUpdate) SetCreatedBy(v uint32) *ContentModelUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableCreatedBy(v *uint32) *ContentModelUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ContentModelUpdate) AddCreatedBy(v int32) *ContentModelUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ContentModelUpdate) ClearCreatedBy() *ContentModelUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ContentModelUpdate) SetUpdatedBy(v uint32) *ContentModelUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableUpdatedBy(v *uint32) *ContentModelUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ContentModelUpdate) AddUpdatedBy(v int32) *ContentModelUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ContentModelUpdate) ClearUpdatedBy() *ContentModelUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ContentModelUpdate) SetDeletedBy(v uint32) *ContentModelUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableDeletedBy(v *uint32) *ContentModelUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ContentModelUpdate) AddDeletedBy(v int32) *ContentModelUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ContentModelUpdate) ClearDeletedBy() *ContentModelUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ContentModelUpdate) SetSortOrder(v uint32) *ContentModelUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableSortOrder(v *uint32) *ContentModelUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ContentModelUpdate) AddSortOrder(v int32) *ContentModelUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *ContentModelUpdate) ClearSortOrder() *ContentModelUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetName sets the "name" field.
func (_u *ContentModelUpdate) SetName(v string) *ContentModelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableName(v *string) *ContentModelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ContentModelUpdate) ClearName() *ContentModelUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetCode sets the "code" field.
func (_u *ContentModelUpdate) SetCode(v string) *ContentModelUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableCode(v *string) *ContentModelUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *ContentModelUpdate) ClearCode() *ContentModelUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ContentModelUpdate) SetDescription(v string) *ContentModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ContentModelUpdate) SetNillableDescription(v *string) *ContentModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ContentModelUpdate) ClearDescription() *ContentModelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ContentModelMutation object of the builder.
func (_u *ContentModelUpdate) Mutation() *ContentModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContentModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContentModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContentModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContentModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContentModelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := contentmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ContentModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := contentmodel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ContentModel.code": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContentModelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContentModelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContentModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contentmodel.Table, contentmodel.Columns, sqlgraph.NewFieldSpec(contentmodel.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(contentmodel.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contentmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(contentmodel.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(contentmodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(contentmodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(contentmodel.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(contentmodel.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(contentmodel.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(contentmodel.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(contentmodel.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(contentmodel.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(contentmodel.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(contentmodel.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(contentmodel.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(contentmodel.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(contentmodel.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(contentmodel.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(contentmodel.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(contentmodel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(contentmodel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(contentmodel.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(contentmodel.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(contentmodel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(contentmodel.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contentmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContentModelUpdateOne is the builder for updating a single ContentModel entity.
type ContentModelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ContentModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContentModelUpdateOne) SetUpdatedAt(v time.Time) *ContentModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableUpdatedAt(v *time.Time) *ContentModelUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ContentModelUpdateOne) ClearUpdatedAt() *ContentModelUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ContentModelUpdateOne) SetDeletedAt(v time.Time) *ContentModelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableDeletedAt(v *time.Time) *ContentModelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ContentModelUpdateOne) ClearDeletedAt() *ContentModelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ContentModelUpdateOne) SetCreatedBy(v uint32) *ContentModelUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableCreatedBy(v *uint32) *ContentModelUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ContentModelUpdateOne) AddCreatedBy(v int32) *ContentModelUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ContentModelUpdateOne) ClearCreatedBy() *ContentModelUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ContentModelUpdateOne) SetUpdatedBy(v uint32) *ContentModelUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableUpdatedBy(v *uint32) *ContentModelUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ContentModelUpdateOne) AddUpdatedBy(v int32) *ContentModelUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ContentModelUpdateOne) ClearUpdatedBy() *ContentModelUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ContentModelUpdateOne) SetDeletedBy(v uint32) *ContentModelUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableDeletedBy(v *uint32) *ContentModelUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ContentModelUpdateOne) AddDeletedBy(v int32) *ContentModelUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ContentModelUpdateOne) ClearDeletedBy() *ContentModelUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ContentModelUpdateOne) SetSortOrder(v uint32) *ContentModelUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableSortOrder(v *uint32) *ContentModelUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ContentModelUpdateOne) AddSortOrder(v int32) *ContentModelUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *ContentModelUpdateOne) ClearSortOrder() *ContentModelUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetName sets the "name" field.
func (_u *ContentModelUpdateOne) SetName(v string) *ContentModelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableName(v *string) *ContentModelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ContentModelUpdateOne) ClearName() *ContentModelUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetCode sets the "code" field.
func (_u *ContentModelUpdateOne) SetCode(v string) *ContentModelUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableCode(v *string) *ContentModelUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *ContentModelUpdateOne) ClearCode() *ContentModelUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ContentModelUpdateOne) SetDescription(v string) *ContentModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ContentModelUpdateOne) SetNillableDescription(v *string) *ContentModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ContentModelUpdateOne) ClearDescription() *ContentModelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the ContentModelMutation object of the builder.
func (_u *ContentModelUpdateOne) Mutation() *ContentModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContentModelUpdate builder.
func (_u *ContentModelUpdateOne) Where(ps ...predicate.ContentModel) *ContentModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContentModelUpdateOne) Select(field string, fields ...string) *ContentModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContentModel entity.
func (_u *ContentModelUpdateOne) Save(ctx context.Context) (*ContentModel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContentModelUpdateOne) SaveX(ctx context.Context) *ContentModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContentModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContentModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContentModelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := contentmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ContentModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := contentmodel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ContentModel.code": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContentModelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContentModelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContentModelUpdateOne) sqlSave(ctx context.Context) (_node *ContentModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contentmodel.Table, contentmodel.Columns, sqlgraph.NewFieldSpec(contentmodel.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContentModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contentmodel.FieldID)
		for _, f := range fields {
			if !contentmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contentmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(contentmodel.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contentmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(contentmodel.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(contentmodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(contentmodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(contentmodel.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(contentmodel.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(contentmodel.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(contentmodel.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(contentmodel.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(contentmodel.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(contentmodel.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(contentmodel.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(contentmodel.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(contentmodel.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(contentmodel.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(contentmodel.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(contentmodel.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(contentmodel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(contentmodel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(contentmodel.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(contentmodel.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(contentmodel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(contentmodel.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ContentModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contentmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
