// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/contentmodel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContentModelCreate is the builder for creating a ContentModel entity.
type ContentModelCreate struct {
	config
	mutation *ContentModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContentModelCreate) SetCreatedAt(v time.Time) *ContentModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableCreatedAt(v *time.Time) *ContentModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContentModelCreate) SetUpdatedAt(v time.Time) *ContentModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableUpdatedAt(v *time.Time) *ContentModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ContentModelCreate) SetDeletedAt(v time.Time) *ContentModelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableDeletedAt(v *time.Time) *ContentModelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ContentModelCreate) SetCreatedBy(v uint32) *ContentModelCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableCreatedBy(v *uint32) *ContentModelCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ContentModelCreate) SetUpdatedBy(v uint32) *ContentModelCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableUpdatedBy(v *uint32) *ContentModelCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ContentModelCreate) SetDeletedBy(v uint32) *ContentModelCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableDeletedBy(v *uint32) *ContentModelCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ContentModelCreate) SetSortOrder(v uint32) *ContentModelCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableSortOrder(v *uint32) *ContentModelCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ContentModelCreate) SetTenantID(v uint32) *ContentModelCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableTenantID(v *uint32) *ContentModelCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ContentModelCreate) SetName(v string) *ContentModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableName(v *string) *ContentModelCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *ContentModelCreate) SetCode(v string) *ContentModelCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableCode(v *string) *ContentModelCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ContentModelCreate) SetDescription(v string) *ContentModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ContentModelCreate) SetNillableDescription(v *string) *ContentModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContentModelCreate) SetID(v uint32) *ContentModelCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ContentModelMutation object of the builder.
func (_c *ContentModelCreate) Mutation() *ContentModelMutation {
	return _c.mutation
}

// Save creates the ContentModel in the database.
func (_c *ContentModelCreate) Save(ctx context.Context) (*ContentModel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContentModelCreate) SaveX(ctx context.Context) *ContentModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContentModelCreate) defaults() error {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := contentmodel.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := contentmodel.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContentModelCreate) check() error {
	if v, ok := _c.mutation.Name(); ok {
		if err := contentmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ContentModel.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := contentmodel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ContentModel.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := contentmodel.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ContentModel.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ContentModelCreate) sqlSave(ctx context.Context) (*ContentModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContentModelCreate) createSpec() (*ContentModel, *sqlgraph.CreateSpec) {
	var (
		_node = &ContentModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contentmodel.Table, sqlgraph.NewFieldSpec(contentmodel.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contentmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contentmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(contentmodel.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(contentmodel.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(contentmodel.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(contentmodel.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(contentmodel.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(contentmodel.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(contentmodel.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(contentmodel.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(contentmodel.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentModelCreate) OnConflict(opts ...sql.ConflictOption) *ContentModelUpsertOne {
	_c.conflict = opts
	return &ContentModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentModelCreate) OnConflictColumns(columns ...string) *ContentModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentModelUpsertOne{
		create: _c,
	}
}

type (
	// ContentModelUpsertOne is the builder for "upsert"-ing
	//  one ContentModel node.
	ContentModelUpsertOne struct {
		create *ContentModelCreate
	}

	// ContentModelUpsert is the "OnConflict" setter.
	ContentModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentModelUpsert) SetUpdatedAt(v time.Time) *ContentModelUpsert {
	u.Set(contentmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateUpdatedAt() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ContentModelUpsert) ClearUpdatedAt() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ContentModelUpsert) SetDeletedAt(v time.Time) *ContentModelUpsert {
	u.Set(contentmodel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateDeletedAt() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ContentModelUpsert) ClearDeletedAt() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ContentModelUpsert) SetCreatedBy(v uint32) *ContentModelUpsert {
	u.Set(contentmodel.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateCreatedBy() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ContentModelUpsert) AddCreatedBy(v uint32) *ContentModelUpsert {
	u.Add(contentmodel.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ContentModelUpsert) ClearCreatedBy() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ContentModelUpsert) SetUpdatedBy(v uint32) *ContentModelUpsert {
	u.Set(contentmodel.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateUpdatedBy() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ContentModelUpsert) AddUpdatedBy(v uint32) *ContentModelUpsert {
	u.Add(contentmodel.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ContentModelUpsert) ClearUpdatedBy() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ContentModelUpsert) SetDeletedBy(v uint32) *ContentModelUpsert {
	u.Set(contentmodel.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateDeletedBy() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ContentModelUpsert) AddDeletedBy(v uint32) *ContentModelUpsert {
	u.Add(contentmodel.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ContentModelUpsert) ClearDeletedBy() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldDeletedBy)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentModelUpsert) SetSortOrder(v uint32) *ContentModelUpsert {
	u.Set(contentmodel.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateSortOrder() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentModelUpsert) AddSortOrder(v uint32) *ContentModelUpsert {
	u.Add(contentmodel.FieldSortOrder, v)
	return u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *ContentModelUpsert) ClearSortOrder() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldSortOrder)
	return u
}

// SetName sets the "name" field.
func (u *ContentModelUpsert) SetName(v string) *ContentModelUpsert {
	u.Set(contentmodel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateName() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *ContentModelUpsert) ClearName() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *ContentModelUpsert) SetCode(v string) *ContentModelUpsert {
	u.Set(contentmodel.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateCode() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *ContentModelUpsert) ClearCode() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldCode)
	return u
}

// SetDescription sets the "description" field.
func (u *ContentModelUpsert) SetDescription(v string) *ContentModelUpsert {
	u.Set(contentmodel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentModelUpsert) UpdateDescription() *ContentModelUpsert {
	u.SetExcluded(contentmodel.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ContentModelUpsert) ClearDescription() *ContentModelUpsert {
	u.SetNull(contentmodel.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(contentmodel.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContentModelUpsertOne) UpdateNewValues() *ContentModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(contentmodel.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(contentmodel.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(contentmodel.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContentModelUpsertOne) Ignore() *ContentModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentModelUpsertOne) DoNothing() *ContentModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentModelCreate.OnConflict
// documentation for more info.
func (u *ContentModelUpsertOne) Update(set func(*ContentModelUpsert)) *ContentModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentModelUpsertOne) SetUpdatedAt(v time.Time) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateUpdatedAt() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ContentModelUpsertOne) ClearUpdatedAt() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ContentModelUpsertOne) SetDeletedAt(v time.Time) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateDeletedAt() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ContentModelUpsertOne) ClearDeletedAt() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ContentModelUpsertOne) SetCreatedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ContentModelUpsertOne) AddCreatedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateCreatedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ContentModelUpsertOne) ClearCreatedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ContentModelUpsertOne) SetUpdatedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ContentModelUpsertOne) AddUpdatedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateUpdatedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ContentModelUpsertOne) ClearUpdatedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ContentModelUpsertOne) SetDeletedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ContentModelUpsertOne) AddDeletedBy(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateDeletedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ContentModelUpsertOne) ClearDeletedBy() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentModelUpsertOne) SetSortOrder(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentModelUpsertOne) AddSortOrder(v uint32) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateSortOrder() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *ContentModelUpsertOne) ClearSortOrder() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearSortOrder()
	})
}

// SetName sets the "name" field.
func (u *ContentModelUpsertOne) SetName(v string) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateName() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *ContentModelUpsertOne) ClearName() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearName()
	})
}

// SetCode sets the "code" field.
func (u *ContentModelUpsertOne) SetCode(v string) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateCode() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *ContentModelUpsertOne) ClearCode() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearCode()
	})
}

// SetDescription sets the "description" field.
func (u *ContentModelUpsertOne) SetDescription(v string) *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentModelUpsertOne) UpdateDescription() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ContentModelUpsertOne) ClearDescription() *ContentModelUpsertOne {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *ContentModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContentModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContentModelUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContentModelUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContentModelCreateBulk is the builder for creating many ContentModel entities in bulk.
type ContentModelCreateBulk struct {
	config
	err      error
	builders []*ContentModelCreate
	conflict []sql.ConflictOption
}

// Save creates the ContentModel entities in the database.
func (_c *ContentModelCreateBulk) Save(ctx context.Context) ([]*ContentModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContentModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContentModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContentModelCreateBulk) SaveX(ctx context.Context) []*ContentModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContentModelUpsertBulk {
	_c.conflict = opts
	return &ContentModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentModelCreateBulk) OnConflictColumns(columns ...string) *ContentModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentModelUpsertBulk{
		create: _c,
	}
}

// ContentModelUpsertBulk is the builder for "upsert"-ing
// a bulk of ContentModel nodes.
type ContentModelUpsertBulk struct {
	create *ContentModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(contentmodel.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContentModelUpsertBulk) UpdateNewValues() *ContentModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(contentmodel.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(contentmodel.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(contentmodel.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContentModelUpsertBulk) Ignore() *ContentModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentModelUpsertBulk) DoNothing() *ContentModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentModelCreateBulk.OnConflict
// documentation for more info.
func (u *ContentModelUpsertBulk) Update(set func(*ContentModelUpsert)) *ContentModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentModelUpsertBulk) SetUpdatedAt(v time.Time) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateUpdatedAt() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ContentModelUpsertBulk) ClearUpdatedAt() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ContentModelUpsertBulk) SetDeletedAt(v time.Time) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateDeletedAt() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ContentModelUpsertBulk) ClearDeletedAt() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ContentModelUpsertBulk) SetCreatedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ContentModelUpsertBulk) AddCreatedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateCreatedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ContentModelUpsertBulk) ClearCreatedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ContentModelUpsertBulk) SetUpdatedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ContentModelUpsertBulk) AddUpdatedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateUpdatedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ContentModelUpsertBulk) ClearUpdatedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ContentModelUpsertBulk) SetDeletedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ContentModelUpsertBulk) AddDeletedBy(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateDeletedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ContentModelUpsertBulk) ClearDeletedBy() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentModelUpsertBulk) SetSortOrder(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentModelUpsertBulk) AddSortOrder(v uint32) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateSortOrder() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *ContentModelUpsertBulk) ClearSortOrder() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearSortOrder()
	})
}

// SetName sets the "name" field.
func (u *ContentModelUpsertBulk) SetName(v string) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateName() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *ContentModelUpsertBulk) ClearName() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearName()
	})
}

// SetCode sets the "code" field.
func (u *ContentModelUpsertBulk) SetCode(v string) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateCode() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *ContentModelUpsertBulk) ClearCode() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearCode()
	})
}

// SetDescription sets the "description" field.
func (u *ContentModelUpsertBulk) SetDescription(v string) *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentModelUpsertBulk) UpdateDescription() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ContentModelUpsertBulk) ClearDescription() *ContentModelUpsertBulk {
	return u.Update(func(s *ContentModelUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *ContentModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContentModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContentModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
