// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/fielddefinition"
	"go-wind-cms/app/core/service/internal/data/ent/schema"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 字段定义表
type FieldDefinition struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 排序值（越小越靠前）
	SortOrder *uint32 `json:"sort_order,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 所属内容模型ID
	ContentModelID *uint32 `json:"content_model_id,omitempty"`
	// 字段名（语言无关，作为 custom_fields 的键）
	Name *string `json:"name,omitempty"`
	// 字段类型
	Type *fielddefinition.Type `json:"type,omitempty"`
	// 字段标签（默认语言）
	Label *string `json:"label,omitempty"`
	// 字段描述（默认语言）
	Description *string `json:"description,omitempty"`
	// 输入框占位符（默认语言）
	Placeholder *string `json:"placeholder,omitempty"`
	// 是否必填
	IsRequired *bool `json:"is_required,omitempty"`
	// 校验正则（仅 text 类适用）
	ValidationRegex *string `json:"validation_regex,omitempty"`
	// 扩展选项（select 类等，预留）
	Options *map[string]string `json:"options,omitempty"`
	// relation 类型字段的引用配置（仅 FIELD_TYPE_RELATION 适用）
	RelationConfig *schema.RelationConfig `json:"relation_config,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FieldDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fielddefinition.FieldOptions, fielddefinition.FieldRelationConfig:
			values[i] = new([]byte)
		case fielddefinition.FieldIsRequired:
			values[i] = new(sql.NullBool)
		case fielddefinition.FieldID, fielddefinition.FieldCreatedBy, fielddefinition.FieldUpdatedBy, fielddefinition.FieldDeletedBy, fielddefinition.FieldSortOrder, fielddefinition.FieldTenantID, fielddefinition.FieldContentModelID:
			values[i] = new(sql.NullInt64)
		case fielddefinition.FieldName, fielddefinition.FieldType, fielddefinition.FieldLabel, fielddefinition.FieldDescription, fielddefinition.FieldPlaceholder, fielddefinition.FieldValidationRegex:
			values[i] = new(sql.NullString)
		case fielddefinition.FieldCreatedAt, fielddefinition.FieldUpdatedAt, fielddefinition.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FieldDefinition fields.
func (_m *FieldDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fielddefinition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case fielddefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case fielddefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case fielddefinition.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case fielddefinition.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case fielddefinition.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case fielddefinition.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case fielddefinition.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = new(uint32)
				*_m.SortOrder = uint32(value.Int64)
			}
		case fielddefinition.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case fielddefinition.FieldContentModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field content_model_id", values[i])
			} else if value.Valid {
				_m.ContentModelID = new(uint32)
				*_m.ContentModelID = uint32(value.Int64)
			}
		case fielddefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case fielddefinition.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(fielddefinition.Type)
				*_m.Type = fielddefinition.Type(value.String)
			}
		case fielddefinition.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = new(string)
				*_m.Label = value.String
			}
		case fielddefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case fielddefinition.FieldPlaceholder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field placeholder", values[i])
			} else if value.Valid {
				_m.Placeholder = new(string)
				*_m.Placeholder = value.String
			}
		case fielddefinition.FieldIsRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_required", values[i])
			} else if value.Valid {
				_m.IsRequired = new(bool)
				*_m.IsRequired = value.Bool
			}
		case fielddefinition.FieldValidationRegex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field validation_regex", values[i])
			} else if value.Valid {
				_m.ValidationRegex = new(string)
				*_m.ValidationRegex = value.String
			}
		case fielddefinition.FieldOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Options); err != nil {
					return fmt.Errorf("unmarshal field options: %w", err)
				}
			}
		case fielddefinition.FieldRelationConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field relation_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RelationConfig); err != nil {
					return fmt.Errorf("unmarshal field relation_config: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FieldDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *FieldDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FieldDefinition.
// Note that you need to call FieldDefinition.Unwrap() before calling this method if this FieldDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FieldDefinition) Update() *FieldDefinitionUpdateOne {
	return NewFieldDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FieldDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FieldDefinition) Unwrap() *FieldDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FieldDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FieldDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("FieldDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SortOrder; v != nil {
		builder.WriteString("sort_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContentModelID; v != nil {
		builder.WriteString("content_model_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Label; v != nil {
		builder.WriteString("label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Placeholder; v != nil {
		builder.WriteString("placeholder=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsRequired; v != nil {
		builder.WriteString("is_required=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValidationRegex; v != nil {
		builder.WriteString("validation_regex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("options=")
	builder.WriteString(fmt.Sprintf("%v", _m.Options))
	builder.WriteString(", ")
	builder.WriteString("relation_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelationConfig))
	builder.WriteByte(')')
	return builder.String()
}

// FieldDefinitions is a parsable slice of FieldDefinition.
type FieldDefinitions []*FieldDefinition
