// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/fielddefinitiontranslation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 字段定义翻译表
type FieldDefinitionTranslation struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 字段定义ID
	FieldDefinitionID *uint32 `json:"field_definition_id,omitempty"`
	// 语言代码（BCP 47，如 zh-CN）
	LanguageCode *string `json:"language_code,omitempty"`
	// 翻译后字段标签
	Label *string `json:"label,omitempty"`
	// 翻译后字段描述
	Description *string `json:"description,omitempty"`
	// 翻译后占位符
	Placeholder  *string `json:"placeholder,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FieldDefinitionTranslation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fielddefinitiontranslation.FieldID, fielddefinitiontranslation.FieldCreatedBy, fielddefinitiontranslation.FieldUpdatedBy, fielddefinitiontranslation.FieldDeletedBy, fielddefinitiontranslation.FieldFieldDefinitionID:
			values[i] = new(sql.NullInt64)
		case fielddefinitiontranslation.FieldLanguageCode, fielddefinitiontranslation.FieldLabel, fielddefinitiontranslation.FieldDescription, fielddefinitiontranslation.FieldPlaceholder:
			values[i] = new(sql.NullString)
		case fielddefinitiontranslation.FieldCreatedAt, fielddefinitiontranslation.FieldUpdatedAt, fielddefinitiontranslation.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FieldDefinitionTranslation fields.
func (_m *FieldDefinitionTranslation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fielddefinitiontranslation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case fielddefinitiontranslation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case fielddefinitiontranslation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case fielddefinitiontranslation.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case fielddefinitiontranslation.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case fielddefinitiontranslation.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case fielddefinitiontranslation.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case fielddefinitiontranslation.FieldFieldDefinitionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field field_definition_id", values[i])
			} else if value.Valid {
				_m.FieldDefinitionID = new(uint32)
				*_m.FieldDefinitionID = uint32(value.Int64)
			}
		case fielddefinitiontranslation.FieldLanguageCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_code", values[i])
			} else if value.Valid {
				_m.LanguageCode = new(string)
				*_m.LanguageCode = value.String
			}
		case fielddefinitiontranslation.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = new(string)
				*_m.Label = value.String
			}
		case fielddefinitiontranslation.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case fielddefinitiontranslation.FieldPlaceholder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field placeholder", values[i])
			} else if value.Valid {
				_m.Placeholder = new(string)
				*_m.Placeholder = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FieldDefinitionTranslation.
// This includes values selected through modifiers, order, etc.
func (_m *FieldDefinitionTranslation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FieldDefinitionTranslation.
// Note that you need to call FieldDefinitionTranslation.Unwrap() before calling this method if this FieldDefinitionTranslation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FieldDefinitionTranslation) Update() *FieldDefinitionTranslationUpdateOne {
	return NewFieldDefinitionTranslationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FieldDefinitionTranslation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FieldDefinitionTranslation) Unwrap() *FieldDefinitionTranslation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FieldDefinitionTranslation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FieldDefinitionTranslation) String() string {
	var builder strings.Builder
	builder.WriteString("FieldDefinitionTranslation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FieldDefinitionID; v != nil {
		builder.WriteString("field_definition_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LanguageCode; v != nil {
		builder.WriteString("language_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Label; v != nil {
		builder.WriteString("label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Placeholder; v != nil {
		builder.WriteString("placeholder=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// FieldDefinitionTranslations is a parsable slice of FieldDefinitionTranslation.
type FieldDefinitionTranslations []*FieldDefinitionTranslation
