// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/fielddefinition"
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"go-wind-cms/app/core/service/internal/data/ent/schema"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FieldDefinitionUpdate is the builder for updating FieldDefinition entities.
type FieldDefinitionUpdate struct {
	config
	hooks     []Hook
	mutation  *FieldDefinitionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FieldDefinitionUpdate builder.
func (_u *FieldDefinitionUpdate) Where(ps ...predicate.FieldDefinition) *FieldDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FieldDefinitionUpdate) SetUpdatedAt(v time.Time) *FieldDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableUpdatedAt(v *time.Time) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FieldDefinitionUpdate) ClearUpdatedAt() *FieldDefinitionUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FieldDefinitionUpdate) SetDeletedAt(v time.Time) *FieldDefinitionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableDeletedAt(v *time.Time) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FieldDefinitionUpdate) ClearDeletedAt() *FieldDefinitionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FieldDefinitionUpdate) SetCreatedBy(v uint32) *FieldDefinitionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableCreatedBy(v *uint32) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FieldDefinitionUpdate) AddCreatedBy(v int32) *FieldDefinitionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FieldDefinitionUpdate) ClearCreatedBy() *FieldDefinitionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FieldDefinitionUpdate) SetUpdatedBy(v uint32) *FieldDefinitionUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableUpdatedBy(v *uint32) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FieldDefinitionUpdate) AddUpdatedBy(v int32) *FieldDefinitionUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FieldDefinitionUpdate) ClearUpdatedBy() *FieldDefinitionUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FieldDefinitionUpdate) SetDeletedBy(v uint32) *FieldDefinitionUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableDeletedBy(v *uint32) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FieldDefinitionUpdate) AddDeletedBy(v int32) *FieldDefinitionUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FieldDefinitionUpdate) ClearDeletedBy() *FieldDefinitionUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FieldDefinitionUpdate) SetSortOrder(v uint32) *FieldDefinitionUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableSortOrder(v *uint32) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FieldDefinitionUpdate) AddSortOrder(v int32) *FieldDefinitionUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *FieldDefinitionUpdate) ClearSortOrder() *FieldDefinitionUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetContentModelID sets the "content_model_id" field.
func (_u *FieldDefinitionUpdate) SetContentModelID(v uint32) *FieldDefinitionUpdate {
	_u.mutation.ResetContentModelID()
	_u.mutation.SetContentModelID(v)
	return _u
}

// SetNillableContentModelID sets the "content_model_id" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableContentModelID(v *uint32) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetContentModelID(*v)
	}
	return _u
}

// AddContentModelID adds value to the "content_model_id" field.
func (_u *FieldDefinitionUpdate) AddContentModelID(v int32) *FieldDefinitionUpdate {
	_u.mutation.AddContentModelID(v)
	return _u
}

// ClearContentModelID clears the value of the "content_model_id" field.
func (_u *FieldDefinitionUpdate) ClearContentModelID() *FieldDefinitionUpdate {
	_u.mutation.ClearContentModelID()
	return _u
}

// SetName sets the "name" field.
func (_u *FieldDefinitionUpdate) SetName(v string) *FieldDefinitionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableName(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *FieldDefinitionUpdate) ClearName() *FieldDefinitionUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetType sets the "type" field.
func (_u *FieldDefinitionUpdate) SetType(v fielddefinition.Type) *FieldDefinitionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableType(v *fielddefinition.Type) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *FieldDefinitionUpdate) ClearType() *FieldDefinitionUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *FieldDefinitionUpdate) SetLabel(v string) *FieldDefinitionUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableLabel(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *FieldDefinitionUpdate) ClearLabel() *FieldDefinitionUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FieldDefinitionUpdate) SetDescription(v string) *FieldDefinitionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableDescription(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FieldDefinitionUpdate) ClearDescription() *FieldDefinitionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceholder sets the "placeholder" field.
func (_u *FieldDefinitionUpdate) SetPlaceholder(v string) *FieldDefinitionUpdate {
	_u.mutation.SetPlaceholder(v)
	return _u
}

// SetNillablePlaceholder sets the "placeholder" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillablePlaceholder(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetPlaceholder(*v)
	}
	return _u
}

// ClearPlaceholder clears the value of the "placeholder" field.
func (_u *FieldDefinitionUpdate) ClearPlaceholder() *FieldDefinitionUpdate {
	_u.mutation.ClearPlaceholder()
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *FieldDefinitionUpdate) SetIsRequired(v bool) *FieldDefinitionUpdate {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableIsRequired(v *bool) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// ClearIsRequired clears the value of the "is_required" field.
func (_u *FieldDefinitionUpdate) ClearIsRequired() *FieldDefinitionUpdate {
	_u.mutation.ClearIsRequired()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *FieldDefinitionUpdate) SetValidationRegex(v string) *FieldDefinitionUpdate {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *FieldDefinitionUpdate) SetNillableValidationRegex(v *string) *FieldDefinitionUpdate {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *FieldDefinitionUpdate) ClearValidationRegex() *FieldDefinitionUpdate {
	_u.mutation.ClearValidationRegex()
	return _u
}

// SetOptions sets the "options" field.
func (_u *FieldDefinitionUpdate) SetOptions(v *map[string]string) *FieldDefinitionUpdate {
	_u.mutation.SetOptions(v)
	return _u
}

// ClearOptions clears the value of the "options" field.
func (_u *FieldDefinitionUpdate) ClearOptions() *FieldDefinitionUpdate {
	_u.mutation.ClearOptions()
	return _u
}

// SetRelationConfig sets the "relation_config" field.
func (_u *FieldDefinitionUpdate) SetRelationConfig(v *schema.RelationConfig) *FieldDefinitionUpdate {
	_u.mutation.SetRelationConfig(v)
	return _u
}

// ClearRelationConfig clears the value of the "relation_config" field.
func (_u *FieldDefinitionUpdate) ClearRelationConfig() *FieldDefinitionUpdate {
	_u.mutation.ClearRelationConfig()
	return _u
}

// Mutation returns the FieldDefinitionMutation object of the builder.
func (_u *FieldDefinitionUpdate) Mutation() *FieldDefinitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FieldDefinitionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FieldDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldDefinitionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := fielddefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := fielddefinition.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FieldDefinitionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FieldDefinitionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FieldDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fielddefinition.Table, fielddefinition.Columns, sqlgraph.NewFieldSpec(fielddefinition.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fielddefinition.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fielddefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fielddefinition.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fielddefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fielddefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(fielddefinition.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(fielddefinition.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(fielddefinition.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(fielddefinition.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(fielddefinition.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(fielddefinition.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(fielddefinition.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(fielddefinition.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(fielddefinition.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(fielddefinition.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(fielddefinition.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(fielddefinition.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(fielddefinition.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ContentModelID(); ok {
		_spec.SetField(fielddefinition.FieldContentModelID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedContentModelID(); ok {
		_spec.AddField(fielddefinition.FieldContentModelID, field.TypeUint32, value)
	}
	if _u.mutation.ContentModelIDCleared() {
		_spec.ClearField(fielddefinition.FieldContentModelID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(fielddefinition.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(fielddefinition.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fielddefinition.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(fielddefinition.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fielddefinition.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(fielddefinition.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(fielddefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(fielddefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Placeholder(); ok {
		_spec.SetField(fielddefinition.FieldPlaceholder, field.TypeString, value)
	}
	if _u.mutation.PlaceholderCleared() {
		_spec.ClearField(fielddefinition.FieldPlaceholder, field.TypeString)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(fielddefinition.FieldIsRequired, field.TypeBool, value)
	}
	if _u.mutation.IsRequiredCleared() {
		_spec.ClearField(fielddefinition.FieldIsRequired, field.TypeBool)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(fielddefinition.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(fielddefinition.FieldValidationRegex, field.TypeString)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(fielddefinition.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.OptionsCleared() {
		_spec.ClearField(fielddefinition.FieldOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.RelationConfig(); ok {
		_spec.SetField(fielddefinition.FieldRelationConfig, field.TypeJSON, value)
	}
	if _u.mutation.RelationConfigCleared() {
		_spec.ClearField(fielddefinition.FieldRelationConfig, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fielddefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FieldDefinitionUpdateOne is the builder for updating a single FieldDefinition entity.
type FieldDefinitionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FieldDefinitionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FieldDefinitionUpdateOne) SetUpdatedAt(v time.Time) *FieldDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableUpdatedAt(v *time.Time) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FieldDefinitionUpdateOne) ClearUpdatedAt() *FieldDefinitionUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FieldDefinitionUpdateOne) SetDeletedAt(v time.Time) *FieldDefinitionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableDeletedAt(v *time.Time) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FieldDefinitionUpdateOne) ClearDeletedAt() *FieldDefinitionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FieldDefinitionUpdateOne) SetCreatedBy(v uint32) *FieldDefinitionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableCreatedBy(v *uint32) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FieldDefinitionUpdateOne) AddCreatedBy(v int32) *FieldDefinitionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FieldDefinitionUpdateOne) ClearCreatedBy() *FieldDefinitionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FieldDefinitionUpdateOne) SetUpdatedBy(v uint32) *FieldDefinitionUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableUpdatedBy(v *uint32) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FieldDefinitionUpdateOne) AddUpdatedBy(v int32) *FieldDefinitionUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FieldDefinitionUpdateOne) ClearUpdatedBy() *FieldDefinitionUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FieldDefinitionUpdateOne) SetDeletedBy(v uint32) *FieldDefinitionUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableDeletedBy(v *uint32) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FieldDefinitionUpdateOne) AddDeletedBy(v int32) *FieldDefinitionUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FieldDefinitionUpdateOne) ClearDeletedBy() *FieldDefinitionUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FieldDefinitionUpdateOne) SetSortOrder(v uint32) *FieldDefinitionUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableSortOrder(v *uint32) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FieldDefinitionUpdateOne) AddSortOrder(v int32) *FieldDefinitionUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *FieldDefinitionUpdateOne) ClearSortOrder() *FieldDefinitionUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetContentModelID sets the "content_model_id" field.
func (_u *FieldDefinitionUpdateOne) SetContentModelID(v uint32) *FieldDefinitionUpdateOne {
	_u.mutation.ResetContentModelID()
	_u.mutation.SetContentModelID(v)
	return _u
}

// SetNillableContentModelID sets the "content_model_id" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableContentModelID(v *uint32) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetContentModelID(*v)
	}
	return _u
}

// AddContentModelID adds value to the "content_model_id" field.
func (_u *FieldDefinitionUpdateOne) AddContentModelID(v int32) *FieldDefinitionUpdateOne {
	_u.mutation.AddContentModelID(v)
	return _u
}

// ClearContentModelID clears the value of the "content_model_id" field.
func (_u *FieldDefinitionUpdateOne) ClearContentModelID() *FieldDefinitionUpdateOne {
	_u.mutation.ClearContentModelID()
	return _u
}

// SetName sets the "name" field.
func (_u *FieldDefinitionUpdateOne) SetName(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableName(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *FieldDefinitionUpdateOne) ClearName() *FieldDefinitionUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetType sets the "type" field.
func (_u *FieldDefinitionUpdateOne) SetType(v fielddefinition.Type) *FieldDefinitionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableType(v *fielddefinition.Type) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *FieldDefinitionUpdateOne) ClearType() *FieldDefinitionUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *FieldDefinitionUpdateOne) SetLabel(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableLabel(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *FieldDefinitionUpdateOne) ClearLabel() *FieldDefinitionUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FieldDefinitionUpdateOne) SetDescription(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableDescription(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FieldDefinitionUpdateOne) ClearDescription() *FieldDefinitionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceholder sets the "placeholder" field.
func (_u *FieldDefinitionUpdateOne) SetPlaceholder(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetPlaceholder(v)
	return _u
}

// SetNillablePlaceholder sets the "placeholder" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillablePlaceholder(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetPlaceholder(*v)
	}
	return _u
}

// ClearPlaceholder clears the value of the "placeholder" field.
func (_u *FieldDefinitionUpdateOne) ClearPlaceholder() *FieldDefinitionUpdateOne {
	_u.mutation.ClearPlaceholder()
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *FieldDefinitionUpdateOne) SetIsRequired(v bool) *FieldDefinitionUpdateOne {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableIsRequired(v *bool) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// ClearIsRequired clears the value of the "is_required" field.
func (_u *FieldDefinitionUpdateOne) ClearIsRequired() *FieldDefinitionUpdateOne {
	_u.mutation.ClearIsRequired()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *FieldDefinitionUpdateOne) SetValidationRegex(v string) *FieldDefinitionUpdateOne {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *FieldDefinitionUpdateOne) SetNillableValidationRegex(v *string) *FieldDefinitionUpdateOne {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *FieldDefinitionUpdateOne) ClearValidationRegex() *FieldDefinitionUpdateOne {
	_u.mutation.ClearValidationRegex()
	return _u
}

// SetOptions sets the "options" field.
func (_u *FieldDefinitionUpdateOne) SetOptions(v *map[string]string) *FieldDefinitionUpdateOne {
	_u.mutation.SetOptions(v)
	return _u
}

// ClearOptions clears the value of the "options" field.
func (_u *FieldDefinitionUpdateOne) ClearOptions() *FieldDefinitionUpdateOne {
	_u.mutation.ClearOptions()
	return _u
}

// SetRelationConfig sets the "relation_config" field.
func (_u *FieldDefinitionUpdateOne) SetRelationConfig(v *schema.RelationConfig) *FieldDefinitionUpdateOne {
	_u.mutation.SetRelationConfig(v)
	return _u
}

// ClearRelationConfig clears the value of the "relation_config" field.
func (_u *FieldDefinitionUpdateOne) ClearRelationConfig() *FieldDefinitionUpdateOne {
	_u.mutation.ClearRelationConfig()
	return _u
}

// Mutation returns the FieldDefinitionMutation object of the builder.
func (_u *FieldDefinitionUpdateOne) Mutation() *FieldDefinitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the FieldDefinitionUpdate builder.
func (_u *FieldDefinitionUpdateOne) Where(ps ...predicate.FieldDefinition) *FieldDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FieldDefinitionUpdateOne) Select(field string, fields ...string) *FieldDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FieldDefinition entity.
func (_u *FieldDefinitionUpdateOne) Save(ctx context.Context) (*FieldDefinition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldDefinitionUpdateOne) SaveX(ctx context.Context) *FieldDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FieldDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := fielddefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := fielddefinition.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FieldDefinition.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FieldDefinitionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FieldDefinitionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FieldDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *FieldDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fielddefinition.Table, fielddefinition.Columns, sqlgraph.NewFieldSpec(fielddefinition.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FieldDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fielddefinition.FieldID)
		for _, f := range fields {
			if !fielddefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fielddefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(fielddefinition.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fielddefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(fielddefinition.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(fielddefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(fielddefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(fielddefinition.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(fielddefinition.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(fielddefinition.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(fielddefinition.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(fielddefinition.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(fielddefinition.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(fielddefinition.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(fielddefinition.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(fielddefinition.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(fielddefinition.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(fielddefinition.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(fielddefinition.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(fielddefinition.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ContentModelID(); ok {
		_spec.SetField(fielddefinition.FieldContentModelID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedContentModelID(); ok {
		_spec.AddField(fielddefinition.FieldContentModelID, field.TypeUint32, value)
	}
	if _u.mutation.ContentModelIDCleared() {
		_spec.ClearField(fielddefinition.FieldContentModelID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(fielddefinition.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(fielddefinition.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(fielddefinition.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(fielddefinition.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fielddefinition.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(fielddefinition.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(fielddefinition.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(fielddefinition.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Placeholder(); ok {
		_spec.SetField(fielddefinition.FieldPlaceholder, field.TypeString, value)
	}
	if _u.mutation.PlaceholderCleared() {
		_spec.ClearField(fielddefinition.FieldPlaceholder, field.TypeString)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(fielddefinition.FieldIsRequired, field.TypeBool, value)
	}
	if _u.mutation.IsRequiredCleared() {
		_spec.ClearField(fielddefinition.FieldIsRequired, field.TypeBool)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(fielddefinition.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(fielddefinition.FieldValidationRegex, field.TypeString)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(fielddefinition.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.OptionsCleared() {
		_spec.ClearField(fielddefinition.FieldOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.RelationConfig(); ok {
		_spec.SetField(fielddefinition.FieldRelationConfig, field.TypeJSON, value)
	}
	if _u.mutation.RelationConfigCleared() {
		_spec.ClearField(fielddefinition.FieldRelationConfig, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &FieldDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fielddefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
