// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/post"
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks     []Hook
	mutation  *PostMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUpdatedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PostUpdate) ClearUpdatedAt() *PostUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PostUpdate) SetDeletedAt(v time.Time) *PostUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDeletedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PostUpdate) ClearDeletedAt() *PostUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PostUpdate) SetCreatedBy(v uint32) *PostUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCreatedBy(v *uint32) *PostUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PostUpdate) AddCreatedBy(v int32) *PostUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PostUpdate) ClearCreatedBy() *PostUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PostUpdate) SetUpdatedBy(v uint32) *PostUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUpdatedBy(v *uint32) *PostUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PostUpdate) AddUpdatedBy(v int32) *PostUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PostUpdate) ClearUpdatedBy() *PostUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PostUpdate) SetDeletedBy(v uint32) *PostUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDeletedBy(v *uint32) *PostUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PostUpdate) AddDeletedBy(v int32) *PostUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PostUpdate) ClearDeletedBy() *PostUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PostUpdate) SetSortOrder(v uint32) *PostUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSortOrder(v *uint32) *PostUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PostUpdate) AddSortOrder(v int32) *PostUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *PostUpdate) ClearSortOrder() *PostUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdate) SetStatus(v post.Status) *PostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdate) SetNillableStatus(v *post.Status) *PostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *PostUpdate) ClearStatus() *PostUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetEditorType sets the "editor_type" field.
func (_u *PostUpdate) SetEditorType(v post.EditorType) *PostUpdate {
	_u.mutation.SetEditorType(v)
	return _u
}

// SetNillableEditorType sets the "editor_type" field if the given value is not nil.
func (_u *PostUpdate) SetNillableEditorType(v *post.EditorType) *PostUpdate {
	if v != nil {
		_u.SetEditorType(*v)
	}
	return _u
}

// ClearEditorType clears the value of the "editor_type" field.
func (_u *PostUpdate) ClearEditorType() *PostUpdate {
	_u.mutation.ClearEditorType()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdate) SetSlug(v string) *PostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSlug(v *string) *PostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *PostUpdate) ClearSlug() *PostUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetDisallowComment sets the "disallow_comment" field.
func (_u *PostUpdate) SetDisallowComment(v bool) *PostUpdate {
	_u.mutation.SetDisallowComment(v)
	return _u
}

// SetNillableDisallowComment sets the "disallow_comment" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDisallowComment(v *bool) *PostUpdate {
	if v != nil {
		_u.SetDisallowComment(*v)
	}
	return _u
}

// ClearDisallowComment clears the value of the "disallow_comment" field.
func (_u *PostUpdate) ClearDisallowComment() *PostUpdate {
	_u.mutation.ClearDisallowComment()
	return _u
}

// SetInProgress sets the "in_progress" field.
func (_u *PostUpdate) SetInProgress(v bool) *PostUpdate {
	_u.mutation.SetInProgress(v)
	return _u
}

// SetNillableInProgress sets the "in_progress" field if the given value is not nil.
func (_u *PostUpdate) SetNillableInProgress(v *bool) *PostUpdate {
	if v != nil {
		_u.SetInProgress(*v)
	}
	return _u
}

// ClearInProgress clears the value of the "in_progress" field.
func (_u *PostUpdate) ClearInProgress() *PostUpdate {
	_u.mutation.ClearInProgress()
	return _u
}

// SetAutoSummary sets the "auto_summary" field.
func (_u *PostUpdate) SetAutoSummary(v bool) *PostUpdate {
	_u.mutation.SetAutoSummary(v)
	return _u
}

// SetNillableAutoSummary sets the "auto_summary" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAutoSummary(v *bool) *PostUpdate {
	if v != nil {
		_u.SetAutoSummary(*v)
	}
	return _u
}

// ClearAutoSummary clears the value of the "auto_summary" field.
func (_u *PostUpdate) ClearAutoSummary() *PostUpdate {
	_u.mutation.ClearAutoSummary()
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *PostUpdate) SetIsFeatured(v bool) *PostUpdate {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsFeatured(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// ClearIsFeatured clears the value of the "is_featured" field.
func (_u *PostUpdate) ClearIsFeatured() *PostUpdate {
	_u.mutation.ClearIsFeatured()
	return _u
}

// SetVisits sets the "visits" field.
func (_u *PostUpdate) SetVisits(v int32) *PostUpdate {
	_u.mutation.ResetVisits()
	_u.mutation.SetVisits(v)
	return _u
}

// SetNillableVisits sets the "visits" field if the given value is not nil.
func (_u *PostUpdate) SetNillableVisits(v *int32) *PostUpdate {
	if v != nil {
		_u.SetVisits(*v)
	}
	return _u
}

// AddVisits adds value to the "visits" field.
func (_u *PostUpdate) AddVisits(v int32) *PostUpdate {
	_u.mutation.AddVisits(v)
	return _u
}

// ClearVisits clears the value of the "visits" field.
func (_u *PostUpdate) ClearVisits() *PostUpdate {
	_u.mutation.ClearVisits()
	return _u
}

// SetLikes sets the "likes" field.
func (_u *PostUpdate) SetLikes(v int32) *PostUpdate {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLikes(v *int32) *PostUpdate {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *PostUpdate) AddLikes(v int32) *PostUpdate {
	_u.mutation.AddLikes(v)
	return _u
}

// ClearLikes clears the value of the "likes" field.
func (_u *PostUpdate) ClearLikes() *PostUpdate {
	_u.mutation.ClearLikes()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *PostUpdate) SetCommentCount(v int32) *PostUpdate {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCommentCount(v *int32) *PostUpdate {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *PostUpdate) AddCommentCount(v int32) *PostUpdate {
	_u.mutation.AddCommentCount(v)
	return _u
}

// ClearCommentCount clears the value of the "comment_count" field.
func (_u *PostUpdate) ClearCommentCount() *PostUpdate {
	_u.mutation.ClearCommentCount()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdate) SetAuthorID(v uint32) *PostUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthorID(v *uint32) *PostUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *PostUpdate) AddAuthorID(v int32) *PostUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *PostUpdate) ClearAuthorID() *PostUpdate {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *PostUpdate) SetAuthorName(v string) *PostUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthorName(v *string) *PostUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *PostUpdate) ClearAuthorName() *PostUpdate {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PostUpdate) SetPasswordHash(v string) *PostUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePasswordHash(v *string) *PostUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *PostUpdate) ClearPasswordHash() *PostUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetCustomFields sets the "custom_fields" field.
func (_u *PostUpdate) SetCustomFields(v *map[string]string) *PostUpdate {
	_u.mutation.SetCustomFields(v)
	return _u
}

// ClearCustomFields clears the value of the "custom_fields" field.
func (_u *PostUpdate) ClearCustomFields() *PostUpdate {
	_u.mutation.ClearCustomFields()
	return _u
}

// SetCategoryIds sets the "category_ids" field.
func (_u *PostUpdate) SetCategoryIds(v *[]uint32) *PostUpdate {
	_u.mutation.SetCategoryIds(v)
	return _u
}

// ClearCategoryIds clears the value of the "category_ids" field.
func (_u *PostUpdate) ClearCategoryIds() *PostUpdate {
	_u.mutation.ClearCategoryIds()
	return _u
}

// SetTagIds sets the "tag_ids" field.
func (_u *PostUpdate) SetTagIds(v *[]uint32) *PostUpdate {
	_u.mutation.SetTagIds(v)
	return _u
}

// ClearTagIds clears the value of the "tag_ids" field.
func (_u *PostUpdate) ClearTagIds() *PostUpdate {
	_u.mutation.ClearTagIds()
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditorType(); ok {
		if err := post.EditorTypeValidator(v); err != nil {
			return &ValidationError{Name: "editor_type", err: fmt.Errorf(`ent: validator failed for field "Post.editor_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PostUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PostUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(post.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(post.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(post.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(post.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(post.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(post.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(post.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(post.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(post.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(post.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(post.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(post.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(post.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(post.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(post.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(post.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(post.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.EditorType(); ok {
		_spec.SetField(post.FieldEditorType, field.TypeEnum, value)
	}
	if _u.mutation.EditorTypeCleared() {
		_spec.ClearField(post.FieldEditorType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(post.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.DisallowComment(); ok {
		_spec.SetField(post.FieldDisallowComment, field.TypeBool, value)
	}
	if _u.mutation.DisallowCommentCleared() {
		_spec.ClearField(post.FieldDisallowComment, field.TypeBool)
	}
	if value, ok := _u.mutation.InProgress(); ok {
		_spec.SetField(post.FieldInProgress, field.TypeBool, value)
	}
	if _u.mutation.InProgressCleared() {
		_spec.ClearField(post.FieldInProgress, field.TypeBool)
	}
	if value, ok := _u.mutation.AutoSummary(); ok {
		_spec.SetField(post.FieldAutoSummary, field.TypeBool, value)
	}
	if _u.mutation.AutoSummaryCleared() {
		_spec.ClearField(post.FieldAutoSummary, field.TypeBool)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(post.FieldIsFeatured, field.TypeBool, value)
	}
	if _u.mutation.IsFeaturedCleared() {
		_spec.ClearField(post.FieldIsFeatured, field.TypeBool)
	}
	if value, ok := _u.mutation.Visits(); ok {
		_spec.SetField(post.FieldVisits, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVisits(); ok {
		_spec.AddField(post.FieldVisits, field.TypeInt32, value)
	}
	if _u.mutation.VisitsCleared() {
		_spec.ClearField(post.FieldVisits, field.TypeInt32)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(post.FieldLikes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(post.FieldLikes, field.TypeInt32, value)
	}
	if _u.mutation.LikesCleared() {
		_spec.ClearField(post.FieldLikes, field.TypeInt32)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(post.FieldCommentCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(post.FieldCommentCount, field.TypeInt32, value)
	}
	if _u.mutation.CommentCountCleared() {
		_spec.ClearField(post.FieldCommentCount, field.TypeInt32)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(post.FieldAuthorID, field.TypeUint32, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(post.FieldAuthorID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(post.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(post.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(post.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(post.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.CustomFields(); ok {
		_spec.SetField(post.FieldCustomFields, field.TypeJSON, value)
	}
	if _u.mutation.CustomFieldsCleared() {
		_spec.ClearField(post.FieldCustomFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.CategoryIds(); ok {
		_spec.SetField(post.FieldCategoryIds, field.TypeJSON, value)
	}
	if _u.mutation.CategoryIdsCleared() {
		_spec.ClearField(post.FieldCategoryIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TagIds(); ok {
		_spec.SetField(post.FieldTagIds, field.TypeJSON, value)
	}
	if _u.mutation.TagIdsCleared() {
		_spec.ClearField(post.FieldTagIds, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PostMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUpdatedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PostUpdateOne) ClearUpdatedAt() *PostUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PostUpdateOne) SetDeletedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDeletedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PostUpdateOne) ClearDeletedAt() *PostUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PostUpdateOne) SetCreatedBy(v uint32) *PostUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCreatedBy(v *uint32) *PostUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PostUpdateOne) AddCreatedBy(v int32) *PostUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PostUpdateOne) ClearCreatedBy() *PostUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PostUpdateOne) SetUpdatedBy(v uint32) *PostUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUpdatedBy(v *uint32) *PostUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PostUpdateOne) AddUpdatedBy(v int32) *PostUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PostUpdateOne) ClearUpdatedBy() *PostUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PostUpdateOne) SetDeletedBy(v uint32) *PostUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDeletedBy(v *uint32) *PostUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PostUpdateOne) AddDeletedBy(v int32) *PostUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PostUpdateOne) ClearDeletedBy() *PostUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PostUpdateOne) SetSortOrder(v uint32) *PostUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSortOrder(v *uint32) *PostUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PostUpdateOne) AddSortOrder(v int32) *PostUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *PostUpdateOne) ClearSortOrder() *PostUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdateOne) SetStatus(v post.Status) *PostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableStatus(v *post.Status) *PostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *PostUpdateOne) ClearStatus() *PostUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetEditorType sets the "editor_type" field.
func (_u *PostUpdateOne) SetEditorType(v post.EditorType) *PostUpdateOne {
	_u.mutation.SetEditorType(v)
	return _u
}

// SetNillableEditorType sets the "editor_type" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableEditorType(v *post.EditorType) *PostUpdateOne {
	if v != nil {
		_u.SetEditorType(*v)
	}
	return _u
}

// ClearEditorType clears the value of the "editor_type" field.
func (_u *PostUpdateOne) ClearEditorType() *PostUpdateOne {
	_u.mutation.ClearEditorType()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdateOne) SetSlug(v string) *PostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSlug(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *PostUpdateOne) ClearSlug() *PostUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetDisallowComment sets the "disallow_comment" field.
func (_u *PostUpdateOne) SetDisallowComment(v bool) *PostUpdateOne {
	_u.mutation.SetDisallowComment(v)
	return _u
}

// SetNillableDisallowComment sets the "disallow_comment" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDisallowComment(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetDisallowComment(*v)
	}
	return _u
}

// ClearDisallowComment clears the value of the "disallow_comment" field.
func (_u *PostUpdateOne) ClearDisallowComment() *PostUpdateOne {
	_u.mutation.ClearDisallowComment()
	return _u
}

// SetInProgress sets the "in_progress" field.
func (_u *PostUpdateOne) SetInProgress(v bool) *PostUpdateOne {
	_u.mutation.SetInProgress(v)
	return _u
}

// SetNillableInProgress sets the "in_progress" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableInProgress(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetInProgress(*v)
	}
	return _u
}

// ClearInProgress clears the value of the "in_progress" field.
func (_u *PostUpdateOne) ClearInProgress() *PostUpdateOne {
	_u.mutation.ClearInProgress()
	return _u
}

// SetAutoSummary sets the "auto_summary" field.
func (_u *PostUpdateOne) SetAutoSummary(v bool) *PostUpdateOne {
	_u.mutation.SetAutoSummary(v)
	return _u
}

// SetNillableAutoSummary sets the "auto_summary" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAutoSummary(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetAutoSummary(*v)
	}
	return _u
}

// ClearAutoSummary clears the value of the "auto_summary" field.
func (_u *PostUpdateOne) ClearAutoSummary() *PostUpdateOne {
	_u.mutation.ClearAutoSummary()
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *PostUpdateOne) SetIsFeatured(v bool) *PostUpdateOne {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsFeatured(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// ClearIsFeatured clears the value of the "is_featured" field.
func (_u *PostUpdateOne) ClearIsFeatured() *PostUpdateOne {
	_u.mutation.ClearIsFeatured()
	return _u
}

// SetVisits sets the "visits" field.
func (_u *PostUpdateOne) SetVisits(v int32) *PostUpdateOne {
	_u.mutation.ResetVisits()
	_u.mutation.SetVisits(v)
	return _u
}

// SetNillableVisits sets the "visits" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableVisits(v *int32) *PostUpdateOne {
	if v != nil {
		_u.SetVisits(*v)
	}
	return _u
}

// AddVisits adds value to the "visits" field.
func (_u *PostUpdateOne) AddVisits(v int32) *PostUpdateOne {
	_u.mutation.AddVisits(v)
	return _u
}

// ClearVisits clears the value of the "visits" field.
func (_u *PostUpdateOne) ClearVisits() *PostUpdateOne {
	_u.mutation.ClearVisits()
	return _u
}

// SetLikes sets the "likes" field.
func (_u *PostUpdateOne) SetLikes(v int32) *PostUpdateOne {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLikes(v *int32) *PostUpdateOne {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *PostUpdateOne) AddLikes(v int32) *PostUpdateOne {
	_u.mutation.AddLikes(v)
	return _u
}

// ClearLikes clears the value of the "likes" field.
func (_u *PostUpdateOne) ClearLikes() *PostUpdateOne {
	_u.mutation.ClearLikes()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *PostUpdateOne) SetCommentCount(v int32) *PostUpdateOne {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCommentCount(v *int32) *PostUpdateOne {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *PostUpdateOne) AddCommentCount(v int32) *PostUpdateOne {
	_u.mutation.AddCommentCount(v)
	return _u
}

// ClearCommentCount clears the value of the "comment_count" field.
func (_u *PostUpdateOne) ClearCommentCount() *PostUpdateOne {
	_u.mutation.ClearCommentCount()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdateOne) SetAuthorID(v uint32) *PostUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthorID(v *uint32) *PostUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *PostUpdateOne) AddAuthorID(v int32) *PostUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *PostUpdateOne) ClearAuthorID() *PostUpdateOne {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *PostUpdateOne) SetAuthorName(v string) *PostUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthorName(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *PostUpdateOne) ClearAuthorName() *PostUpdateOne {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PostUpdateOne) SetPasswordHash(v string) *PostUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePasswordHash(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *PostUpdateOne) ClearPasswordHash() *PostUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetCustomFields sets the "custom_fields" field.
func (_u *PostUpdateOne) SetCustomFields(v *map[string]string) *PostUpdateOne {
	_u.mutation.SetCustomFields(v)
	return _u
}

// ClearCustomFields clears the value of the "custom_fields" field.
func (_u *PostUpdateOne) ClearCustomFields() *PostUpdateOne {
	_u.mutation.ClearCustomFields()
	return _u
}

// SetCategoryIds sets the "category_ids" field.
func (_u *PostUpdateOne) SetCategoryIds(v *[]uint32) *PostUpdateOne {
	_u.mutation.SetCategoryIds(v)
	return _u
}

// ClearCategoryIds clears the value of the "category_ids" field.
func (_u *PostUpdateOne) ClearCategoryIds() *PostUpdateOne {
	_u.mutation.ClearCategoryIds()
	return _u
}

// SetTagIds sets the "tag_ids" field.
func (_u *PostUpdateOne) SetTagIds(v *[]uint32) *PostUpdateOne {
	_u.mutation.SetTagIds(v)
	return _u
}

// ClearTagIds clears the value of the "tag_ids" field.
func (_u *PostUpdateOne) ClearTagIds() *PostUpdateOne {
	_u.mutation.ClearTagIds()
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditorType(); ok {
		if err := post.EditorTypeValidator(v); err != nil {
			return &ValidationError{Name: "editor_type", err: fmt.Errorf(`ent: validator failed for field "Post.editor_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PostUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PostUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(post.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(post.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(post.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(post.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(post.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(post.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(post.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(post.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(post.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(post.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(post.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(post.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(post.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(post.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(post.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(post.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(post.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.EditorType(); ok {
		_spec.SetField(post.FieldEditorType, field.TypeEnum, value)
	}
	if _u.mutation.EditorTypeCleared() {
		_spec.ClearField(post.FieldEditorType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(post.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.DisallowComment(); ok {
		_spec.SetField(post.FieldDisallowComment, field.TypeBool, value)
	}
	if _u.mutation.DisallowCommentCleared() {
		_spec.ClearField(post.FieldDisallowComment, field.TypeBool)
	}
	if value, ok := _u.mutation.InProgress(); ok {
		_spec.SetField(post.FieldInProgress, field.TypeBool, value)
	}
	if _u.mutation.InProgressCleared() {
		_spec.ClearField(post.FieldInProgress, field.TypeBool)
	}
	if value, ok := _u.mutation.AutoSummary(); ok {
		_spec.SetField(post.FieldAutoSummary, field.TypeBool, value)
	}
	if _u.mutation.AutoSummaryCleared() {
		_spec.ClearField(post.FieldAutoSummary, field.TypeBool)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(post.FieldIsFeatured, field.TypeBool, value)
	}
	if _u.mutation.IsFeaturedCleared() {
		_spec.ClearField(post.FieldIsFeatured, field.TypeBool)
	}
	if value, ok := _u.mutation.Visits(); ok {
		_spec.SetField(post.FieldVisits, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVisits(); ok {
		_spec.AddField(post.FieldVisits, field.TypeInt32, value)
	}
	if _u.mutation.VisitsCleared() {
		_spec.ClearField(post.FieldVisits, field.TypeInt32)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(post.FieldLikes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(post.FieldLikes, field.TypeInt32, value)
	}
	if _u.mutation.LikesCleared() {
		_spec.ClearField(post.FieldLikes, field.TypeInt32)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(post.FieldCommentCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(post.FieldCommentCount, field.TypeInt32, value)
	}
	if _u.mutation.CommentCountCleared() {
		_spec.ClearField(post.FieldCommentCount, field.TypeInt32)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(post.FieldAuthorID, field.TypeUint32, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(post.FieldAuthorID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(post.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(post.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(post.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(post.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.CustomFields(); ok {
		_spec.SetField(post.FieldCustomFields, field.TypeJSON, value)
	}
	if _u.mutation.CustomFieldsCleared() {
		_spec.ClearField(post.FieldCustomFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.CategoryIds(); ok {
		_spec.SetField(post.FieldCategoryIds, field.TypeJSON, value)
	}
	if _u.mutation.CategoryIdsCleared() {
		_spec.ClearField(post.FieldCategoryIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TagIds(); ok {
		_spec.SetField(post.FieldTagIds, field.TypeJSON, value)
	}
	if _u.mutation.TagIdsCleared() {
		_spec.ClearField(post.FieldTagIds, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
