// Code generated by ent, DO NOT EDIT.

package pagetranslation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pagetranslation type in the database.
	Label = "page_translation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldPageID holds the string denoting the page_id field in the database.
	FieldPageID = "page_id"
	// FieldLanguageCode holds the string denoting the language_code field in the database.
	FieldLanguageCode = "language_code"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldOriginalContent holds the string denoting the original_content field in the database.
	FieldOriginalContent = "original_content"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldCoverImage holds the string denoting the cover_image field in the database.
	FieldCoverImage = "cover_image"
	// FieldFullPath holds the string denoting the full_path field in the database.
	FieldFullPath = "full_path"
	// FieldWordCount holds the string denoting the word_count field in the database.
	FieldWordCount = "word_count"
	// FieldMetaKeywords holds the string denoting the meta_keywords field in the database.
	FieldMetaKeywords = "meta_keywords"
	// FieldMetaDescription holds the string denoting the meta_description field in the database.
	FieldMetaDescription = "meta_description"
	// FieldSeoTitle holds the string denoting the seo_title field in the database.
	FieldSeoTitle = "seo_title"
	// Table holds the table name of the pagetranslation in the database.
	Table = "page_translations"
)

// Columns holds all SQL columns for pagetranslation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldPageID,
	FieldLanguageCode,
	FieldTitle,
	FieldSlug,
	FieldSummary,
	FieldContent,
	FieldOriginalContent,
	FieldThumbnail,
	FieldCoverImage,
	FieldFullPath,
	FieldWordCount,
	FieldMetaKeywords,
	FieldMetaDescription,
	FieldSeoTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the PageTranslation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByPageID orders the results by the page_id field.
func ByPageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageID, opts...).ToFunc()
}

// ByLanguageCode orders the results by the language_code field.
func ByLanguageCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguageCode, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByOriginalContent orders the results by the original_content field.
func ByOriginalContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalContent, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}

// ByCoverImage orders the results by the cover_image field.
func ByCoverImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImage, opts...).ToFunc()
}

// ByFullPath orders the results by the full_path field.
func ByFullPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullPath, opts...).ToFunc()
}

// ByWordCount orders the results by the word_count field.
func ByWordCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWordCount, opts...).ToFunc()
}

// ByMetaKeywords orders the results by the meta_keywords field.
func ByMetaKeywords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetaKeywords, opts...).ToFunc()
}

// ByMetaDescription orders the results by the meta_description field.
func ByMetaDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetaDescription, opts...).ToFunc()
}

// BySeoTitle orders the results by the seo_title field.
func BySeoTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoTitle, opts...).ToFunc()
}
