// Code generated by ent, DO NOT EDIT.

package pagetranslation

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// PageID applies equality check predicate on the "page_id" field. It's identical to PageIDEQ.
func PageID(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldPageID, v))
}

// LanguageCode applies equality check predicate on the "language_code" field. It's identical to LanguageCodeEQ.
func LanguageCode(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSlug, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSummary, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldContent, v))
}

// OriginalContent applies equality check predicate on the "original_content" field. It's identical to OriginalContentEQ.
func OriginalContent(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldOriginalContent, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldThumbnail, v))
}

// CoverImage applies equality check predicate on the "cover_image" field. It's identical to CoverImageEQ.
func CoverImage(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCoverImage, v))
}

// FullPath applies equality check predicate on the "full_path" field. It's identical to FullPathEQ.
func FullPath(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldFullPath, v))
}

// WordCount applies equality check predicate on the "word_count" field. It's identical to WordCountEQ.
func WordCount(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldWordCount, v))
}

// MetaKeywords applies equality check predicate on the "meta_keywords" field. It's identical to MetaKeywordsEQ.
func MetaKeywords(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldMetaKeywords, v))
}

// MetaDescription applies equality check predicate on the "meta_description" field. It's identical to MetaDescriptionEQ.
func MetaDescription(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldDeletedBy))
}

// PageIDEQ applies the EQ predicate on the "page_id" field.
func PageIDEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldPageID, v))
}

// PageIDNEQ applies the NEQ predicate on the "page_id" field.
func PageIDNEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldPageID, v))
}

// PageIDIn applies the In predicate on the "page_id" field.
func PageIDIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldPageID, vs...))
}

// PageIDNotIn applies the NotIn predicate on the "page_id" field.
func PageIDNotIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldPageID, vs...))
}

// PageIDGT applies the GT predicate on the "page_id" field.
func PageIDGT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldPageID, v))
}

// PageIDGTE applies the GTE predicate on the "page_id" field.
func PageIDGTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldPageID, v))
}

// PageIDLT applies the LT predicate on the "page_id" field.
func PageIDLT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldPageID, v))
}

// PageIDLTE applies the LTE predicate on the "page_id" field.
func PageIDLTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldPageID, v))
}

// PageIDIsNil applies the IsNil predicate on the "page_id" field.
func PageIDIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldPageID))
}

// PageIDNotNil applies the NotNil predicate on the "page_id" field.
func PageIDNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldPageID))
}

// LanguageCodeEQ applies the EQ predicate on the "language_code" field.
func LanguageCodeEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldLanguageCode, v))
}

// LanguageCodeNEQ applies the NEQ predicate on the "language_code" field.
func LanguageCodeNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldLanguageCode, v))
}

// LanguageCodeIn applies the In predicate on the "language_code" field.
func LanguageCodeIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldLanguageCode, vs...))
}

// LanguageCodeNotIn applies the NotIn predicate on the "language_code" field.
func LanguageCodeNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldLanguageCode, vs...))
}

// LanguageCodeGT applies the GT predicate on the "language_code" field.
func LanguageCodeGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldLanguageCode, v))
}

// LanguageCodeGTE applies the GTE predicate on the "language_code" field.
func LanguageCodeGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldLanguageCode, v))
}

// LanguageCodeLT applies the LT predicate on the "language_code" field.
func LanguageCodeLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldLanguageCode, v))
}

// LanguageCodeLTE applies the LTE predicate on the "language_code" field.
func LanguageCodeLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldLanguageCode, v))
}

// LanguageCodeContains applies the Contains predicate on the "language_code" field.
func LanguageCodeContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldLanguageCode, v))
}

// LanguageCodeHasPrefix applies the HasPrefix predicate on the "language_code" field.
func LanguageCodeHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldLanguageCode, v))
}

// LanguageCodeHasSuffix applies the HasSuffix predicate on the "language_code" field.
func LanguageCodeHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldLanguageCode, v))
}

// LanguageCodeIsNil applies the IsNil predicate on the "language_code" field.
func LanguageCodeIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldLanguageCode))
}

// LanguageCodeNotNil applies the NotNil predicate on the "language_code" field.
func LanguageCodeNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldLanguageCode))
}

// LanguageCodeEqualFold applies the EqualFold predicate on the "language_code" field.
func LanguageCodeEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldLanguageCode, v))
}

// LanguageCodeContainsFold applies the ContainsFold predicate on the "language_code" field.
func LanguageCodeContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldLanguageCode, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldSlug, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldSummary, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldContent, v))
}

// OriginalContentEQ applies the EQ predicate on the "original_content" field.
func OriginalContentEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldOriginalContent, v))
}

// OriginalContentNEQ applies the NEQ predicate on the "original_content" field.
func OriginalContentNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldOriginalContent, v))
}

// OriginalContentIn applies the In predicate on the "original_content" field.
func OriginalContentIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldOriginalContent, vs...))
}

// OriginalContentNotIn applies the NotIn predicate on the "original_content" field.
func OriginalContentNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldOriginalContent, vs...))
}

// OriginalContentGT applies the GT predicate on the "original_content" field.
func OriginalContentGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldOriginalContent, v))
}

// OriginalContentGTE applies the GTE predicate on the "original_content" field.
func OriginalContentGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldOriginalContent, v))
}

// OriginalContentLT applies the LT predicate on the "original_content" field.
func OriginalContentLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldOriginalContent, v))
}

// OriginalContentLTE applies the LTE predicate on the "original_content" field.
func OriginalContentLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldOriginalContent, v))
}

// OriginalContentContains applies the Contains predicate on the "original_content" field.
func OriginalContentContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldOriginalContent, v))
}

// OriginalContentHasPrefix applies the HasPrefix predicate on the "original_content" field.
func OriginalContentHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldOriginalContent, v))
}

// OriginalContentHasSuffix applies the HasSuffix predicate on the "original_content" field.
func OriginalContentHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldOriginalContent, v))
}

// OriginalContentIsNil applies the IsNil predicate on the "original_content" field.
func OriginalContentIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldOriginalContent))
}

// OriginalContentNotNil applies the NotNil predicate on the "original_content" field.
func OriginalContentNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldOriginalContent))
}

// OriginalContentEqualFold applies the EqualFold predicate on the "original_content" field.
func OriginalContentEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldOriginalContent, v))
}

// OriginalContentContainsFold applies the ContainsFold predicate on the "original_content" field.
func OriginalContentContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldOriginalContent, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailIsNil applies the IsNil predicate on the "thumbnail" field.
func ThumbnailIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldThumbnail))
}

// ThumbnailNotNil applies the NotNil predicate on the "thumbnail" field.
func ThumbnailNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldThumbnail))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldThumbnail, v))
}

// CoverImageEQ applies the EQ predicate on the "cover_image" field.
func CoverImageEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageNEQ applies the NEQ predicate on the "cover_image" field.
func CoverImageNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldCoverImage, v))
}

// CoverImageIn applies the In predicate on the "cover_image" field.
func CoverImageIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldCoverImage, vs...))
}

// CoverImageNotIn applies the NotIn predicate on the "cover_image" field.
func CoverImageNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldCoverImage, vs...))
}

// CoverImageGT applies the GT predicate on the "cover_image" field.
func CoverImageGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldCoverImage, v))
}

// CoverImageGTE applies the GTE predicate on the "cover_image" field.
func CoverImageGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldCoverImage, v))
}

// CoverImageLT applies the LT predicate on the "cover_image" field.
func CoverImageLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldCoverImage, v))
}

// CoverImageLTE applies the LTE predicate on the "cover_image" field.
func CoverImageLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldCoverImage, v))
}

// CoverImageContains applies the Contains predicate on the "cover_image" field.
func CoverImageContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldCoverImage, v))
}

// CoverImageHasPrefix applies the HasPrefix predicate on the "cover_image" field.
func CoverImageHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldCoverImage, v))
}

// CoverImageHasSuffix applies the HasSuffix predicate on the "cover_image" field.
func CoverImageHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldCoverImage, v))
}

// CoverImageIsNil applies the IsNil predicate on the "cover_image" field.
func CoverImageIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldCoverImage))
}

// CoverImageNotNil applies the NotNil predicate on the "cover_image" field.
func CoverImageNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldCoverImage))
}

// CoverImageEqualFold applies the EqualFold predicate on the "cover_image" field.
func CoverImageEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldCoverImage, v))
}

// CoverImageContainsFold applies the ContainsFold predicate on the "cover_image" field.
func CoverImageContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldCoverImage, v))
}

// FullPathEQ applies the EQ predicate on the "full_path" field.
func FullPathEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldFullPath, v))
}

// FullPathNEQ applies the NEQ predicate on the "full_path" field.
func FullPathNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldFullPath, v))
}

// FullPathIn applies the In predicate on the "full_path" field.
func FullPathIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldFullPath, vs...))
}

// FullPathNotIn applies the NotIn predicate on the "full_path" field.
func FullPathNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldFullPath, vs...))
}

// FullPathGT applies the GT predicate on the "full_path" field.
func FullPathGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldFullPath, v))
}

// FullPathGTE applies the GTE predicate on the "full_path" field.
func FullPathGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldFullPath, v))
}

// FullPathLT applies the LT predicate on the "full_path" field.
func FullPathLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldFullPath, v))
}

// FullPathLTE applies the LTE predicate on the "full_path" field.
func FullPathLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldFullPath, v))
}

// FullPathContains applies the Contains predicate on the "full_path" field.
func FullPathContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldFullPath, v))
}

// FullPathHasPrefix applies the HasPrefix predicate on the "full_path" field.
func FullPathHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldFullPath, v))
}

// FullPathHasSuffix applies the HasSuffix predicate on the "full_path" field.
func FullPathHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldFullPath, v))
}

// FullPathIsNil applies the IsNil predicate on the "full_path" field.
func FullPathIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldFullPath))
}

// FullPathNotNil applies the NotNil predicate on the "full_path" field.
func FullPathNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldFullPath))
}

// FullPathEqualFold applies the EqualFold predicate on the "full_path" field.
func FullPathEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldFullPath, v))
}

// FullPathContainsFold applies the ContainsFold predicate on the "full_path" field.
func FullPathContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldFullPath, v))
}

// WordCountEQ applies the EQ predicate on the "word_count" field.
func WordCountEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldWordCount, v))
}

// WordCountNEQ applies the NEQ predicate on the "word_count" field.
func WordCountNEQ(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldWordCount, v))
}

// WordCountIn applies the In predicate on the "word_count" field.
func WordCountIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldWordCount, vs...))
}

// WordCountNotIn applies the NotIn predicate on the "word_count" field.
func WordCountNotIn(vs ...uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldWordCount, vs...))
}

// WordCountGT applies the GT predicate on the "word_count" field.
func WordCountGT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldWordCount, v))
}

// WordCountGTE applies the GTE predicate on the "word_count" field.
func WordCountGTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldWordCount, v))
}

// WordCountLT applies the LT predicate on the "word_count" field.
func WordCountLT(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldWordCount, v))
}

// WordCountLTE applies the LTE predicate on the "word_count" field.
func WordCountLTE(v uint32) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldWordCount, v))
}

// WordCountIsNil applies the IsNil predicate on the "word_count" field.
func WordCountIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldWordCount))
}

// WordCountNotNil applies the NotNil predicate on the "word_count" field.
func WordCountNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldWordCount))
}

// MetaKeywordsEQ applies the EQ predicate on the "meta_keywords" field.
func MetaKeywordsEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldMetaKeywords, v))
}

// MetaKeywordsNEQ applies the NEQ predicate on the "meta_keywords" field.
func MetaKeywordsNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldMetaKeywords, v))
}

// MetaKeywordsIn applies the In predicate on the "meta_keywords" field.
func MetaKeywordsIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldMetaKeywords, vs...))
}

// MetaKeywordsNotIn applies the NotIn predicate on the "meta_keywords" field.
func MetaKeywordsNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldMetaKeywords, vs...))
}

// MetaKeywordsGT applies the GT predicate on the "meta_keywords" field.
func MetaKeywordsGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldMetaKeywords, v))
}

// MetaKeywordsGTE applies the GTE predicate on the "meta_keywords" field.
func MetaKeywordsGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldMetaKeywords, v))
}

// MetaKeywordsLT applies the LT predicate on the "meta_keywords" field.
func MetaKeywordsLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldMetaKeywords, v))
}

// MetaKeywordsLTE applies the LTE predicate on the "meta_keywords" field.
func MetaKeywordsLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldMetaKeywords, v))
}

// MetaKeywordsContains applies the Contains predicate on the "meta_keywords" field.
func MetaKeywordsContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldMetaKeywords, v))
}

// MetaKeywordsHasPrefix applies the HasPrefix predicate on the "meta_keywords" field.
func MetaKeywordsHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldMetaKeywords, v))
}

// MetaKeywordsHasSuffix applies the HasSuffix predicate on the "meta_keywords" field.
func MetaKeywordsHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldMetaKeywords, v))
}

// MetaKeywordsIsNil applies the IsNil predicate on the "meta_keywords" field.
func MetaKeywordsIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldMetaKeywords))
}

// MetaKeywordsNotNil applies the NotNil predicate on the "meta_keywords" field.
func MetaKeywordsNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldMetaKeywords))
}

// MetaKeywordsEqualFold applies the EqualFold predicate on the "meta_keywords" field.
func MetaKeywordsEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldMetaKeywords, v))
}

// MetaKeywordsContainsFold applies the ContainsFold predicate on the "meta_keywords" field.
func MetaKeywordsContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldMetaKeywords, v))
}

// MetaDescriptionEQ applies the EQ predicate on the "meta_description" field.
func MetaDescriptionEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldMetaDescription, v))
}

// MetaDescriptionNEQ applies the NEQ predicate on the "meta_description" field.
func MetaDescriptionNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldMetaDescription, v))
}

// MetaDescriptionIn applies the In predicate on the "meta_description" field.
func MetaDescriptionIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldMetaDescription, vs...))
}

// MetaDescriptionNotIn applies the NotIn predicate on the "meta_description" field.
func MetaDescriptionNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldMetaDescription, vs...))
}

// MetaDescriptionGT applies the GT predicate on the "meta_description" field.
func MetaDescriptionGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldMetaDescription, v))
}

// MetaDescriptionGTE applies the GTE predicate on the "meta_description" field.
func MetaDescriptionGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldMetaDescription, v))
}

// MetaDescriptionLT applies the LT predicate on the "meta_description" field.
func MetaDescriptionLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldMetaDescription, v))
}

// MetaDescriptionLTE applies the LTE predicate on the "meta_description" field.
func MetaDescriptionLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldMetaDescription, v))
}

// MetaDescriptionContains applies the Contains predicate on the "meta_description" field.
func MetaDescriptionContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldMetaDescription, v))
}

// MetaDescriptionHasPrefix applies the HasPrefix predicate on the "meta_description" field.
func MetaDescriptionHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldMetaDescription, v))
}

// MetaDescriptionHasSuffix applies the HasSuffix predicate on the "meta_description" field.
func MetaDescriptionHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldMetaDescription, v))
}

// MetaDescriptionIsNil applies the IsNil predicate on the "meta_description" field.
func MetaDescriptionIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldMetaDescription))
}

// MetaDescriptionNotNil applies the NotNil predicate on the "meta_description" field.
func MetaDescriptionNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldMetaDescription))
}

// MetaDescriptionEqualFold applies the EqualFold predicate on the "meta_description" field.
func MetaDescriptionEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldMetaDescription, v))
}

// MetaDescriptionContainsFold applies the ContainsFold predicate on the "meta_description" field.
func MetaDescriptionContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldMetaDescription, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleIsNil applies the IsNil predicate on the "seo_title" field.
func SeoTitleIsNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldIsNull(FieldSeoTitle))
}

// SeoTitleNotNil applies the NotNil predicate on the "seo_title" field.
func SeoTitleNotNil() predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldNotNull(FieldSeoTitle))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.PageTranslation {
	return predicate.PageTranslation(sql.FieldContainsFold(FieldSeoTitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PageTranslation) predicate.PageTranslation {
	return predicate.PageTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PageTranslation) predicate.PageTranslation {
	return predicate.PageTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PageTranslation) predicate.PageTranslation {
	return predicate.PageTranslation(sql.NotPredicates(p))
}
