/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'category-list': RouteRecordInfo<'category-list', '/category', Record<never, never>, Record<never, never>>,
    'category-detail': RouteRecordInfo<'category-detail', '/category/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/editor-demo': RouteRecordInfo<'/editor-demo', '/editor-demo', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'post-list': RouteRecordInfo<'post-list', '/post', Record<never, never>, Record<never, never>>,
    'post-detail': RouteRecordInfo<'post-detail', '/post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    '/test-navigation': RouteRecordInfo<'/test-navigation', '/test-navigation', Record<never, never>, Record<never, never>>,
    '/viewer-demo': RouteRecordInfo<'/viewer-demo', '/viewer-demo', Record<never, never>, Record<never, never>>,
    'workbench': RouteRecordInfo<'workbench', '/workbench', Record<never, never>, Record<never, never>>,
  }
}
