// Code generated by ent, DO NOT EDIT.

package fielddefinition

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDeletedBy, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldSortOrder, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldTenantID, v))
}

// ContentModelID applies equality check predicate on the "content_model_id" field. It's identical to ContentModelIDEQ.
func ContentModelID(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldContentModelID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDescription, v))
}

// Placeholder applies equality check predicate on the "placeholder" field. It's identical to PlaceholderEQ.
func Placeholder(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldPlaceholder, v))
}

// IsRequired applies equality check predicate on the "is_required" field. It's identical to IsRequiredEQ.
func IsRequired(v bool) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldIsRequired, v))
}

// ValidationRegex applies equality check predicate on the "validation_regex" field. It's identical to ValidationRegexEQ.
func ValidationRegex(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldValidationRegex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldDeletedBy))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldSortOrder, v))
}

// SortOrderIsNil applies the IsNil predicate on the "sort_order" field.
func SortOrderIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldSortOrder))
}

// SortOrderNotNil applies the NotNil predicate on the "sort_order" field.
func SortOrderNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldSortOrder))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldTenantID))
}

// ContentModelIDEQ applies the EQ predicate on the "content_model_id" field.
func ContentModelIDEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldContentModelID, v))
}

// ContentModelIDNEQ applies the NEQ predicate on the "content_model_id" field.
func ContentModelIDNEQ(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldContentModelID, v))
}

// ContentModelIDIn applies the In predicate on the "content_model_id" field.
func ContentModelIDIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldContentModelID, vs...))
}

// ContentModelIDNotIn applies the NotIn predicate on the "content_model_id" field.
func ContentModelIDNotIn(vs ...uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldContentModelID, vs...))
}

// ContentModelIDGT applies the GT predicate on the "content_model_id" field.
func ContentModelIDGT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldContentModelID, v))
}

// ContentModelIDGTE applies the GTE predicate on the "content_model_id" field.
func ContentModelIDGTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldContentModelID, v))
}

// ContentModelIDLT applies the LT predicate on the "content_model_id" field.
func ContentModelIDLT(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldContentModelID, v))
}

// ContentModelIDLTE applies the LTE predicate on the "content_model_id" field.
func ContentModelIDLTE(v uint32) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldContentModelID, v))
}

// ContentModelIDIsNil applies the IsNil predicate on the "content_model_id" field.
func ContentModelIDIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldContentModelID))
}

// ContentModelIDNotNil applies the NotNil predicate on the "content_model_id" field.
func ContentModelIDNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldContentModelID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldType, vs...))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldType))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContainsFold(FieldLabel, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// PlaceholderEQ applies the EQ predicate on the "placeholder" field.
func PlaceholderEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldPlaceholder, v))
}

// PlaceholderNEQ applies the NEQ predicate on the "placeholder" field.
func PlaceholderNEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldPlaceholder, v))
}

// PlaceholderIn applies the In predicate on the "placeholder" field.
func PlaceholderIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldPlaceholder, vs...))
}

// PlaceholderNotIn applies the NotIn predicate on the "placeholder" field.
func PlaceholderNotIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldPlaceholder, vs...))
}

// PlaceholderGT applies the GT predicate on the "placeholder" field.
func PlaceholderGT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldPlaceholder, v))
}

// PlaceholderGTE applies the GTE predicate on the "placeholder" field.
func PlaceholderGTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldPlaceholder, v))
}

// PlaceholderLT applies the LT predicate on the "placeholder" field.
func PlaceholderLT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldPlaceholder, v))
}

// PlaceholderLTE applies the LTE predicate on the "placeholder" field.
func PlaceholderLTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldPlaceholder, v))
}

// PlaceholderContains applies the Contains predicate on the "placeholder" field.
func PlaceholderContains(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContains(FieldPlaceholder, v))
}

// PlaceholderHasPrefix applies the HasPrefix predicate on the "placeholder" field.
func PlaceholderHasPrefix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasPrefix(FieldPlaceholder, v))
}

// PlaceholderHasSuffix applies the HasSuffix predicate on the "placeholder" field.
func PlaceholderHasSuffix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasSuffix(FieldPlaceholder, v))
}

// PlaceholderIsNil applies the IsNil predicate on the "placeholder" field.
func PlaceholderIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldPlaceholder))
}

// PlaceholderNotNil applies the NotNil predicate on the "placeholder" field.
func PlaceholderNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldPlaceholder))
}

// PlaceholderEqualFold applies the EqualFold predicate on the "placeholder" field.
func PlaceholderEqualFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEqualFold(FieldPlaceholder, v))
}

// PlaceholderContainsFold applies the ContainsFold predicate on the "placeholder" field.
func PlaceholderContainsFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContainsFold(FieldPlaceholder, v))
}

// IsRequiredEQ applies the EQ predicate on the "is_required" field.
func IsRequiredEQ(v bool) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldIsRequired, v))
}

// IsRequiredNEQ applies the NEQ predicate on the "is_required" field.
func IsRequiredNEQ(v bool) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldIsRequired, v))
}

// IsRequiredIsNil applies the IsNil predicate on the "is_required" field.
func IsRequiredIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldIsRequired))
}

// IsRequiredNotNil applies the NotNil predicate on the "is_required" field.
func IsRequiredNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldIsRequired))
}

// ValidationRegexEQ applies the EQ predicate on the "validation_regex" field.
func ValidationRegexEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEQ(FieldValidationRegex, v))
}

// ValidationRegexNEQ applies the NEQ predicate on the "validation_regex" field.
func ValidationRegexNEQ(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNEQ(FieldValidationRegex, v))
}

// ValidationRegexIn applies the In predicate on the "validation_regex" field.
func ValidationRegexIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIn(FieldValidationRegex, vs...))
}

// ValidationRegexNotIn applies the NotIn predicate on the "validation_regex" field.
func ValidationRegexNotIn(vs ...string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotIn(FieldValidationRegex, vs...))
}

// ValidationRegexGT applies the GT predicate on the "validation_regex" field.
func ValidationRegexGT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGT(FieldValidationRegex, v))
}

// ValidationRegexGTE applies the GTE predicate on the "validation_regex" field.
func ValidationRegexGTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldGTE(FieldValidationRegex, v))
}

// ValidationRegexLT applies the LT predicate on the "validation_regex" field.
func ValidationRegexLT(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLT(FieldValidationRegex, v))
}

// ValidationRegexLTE applies the LTE predicate on the "validation_regex" field.
func ValidationRegexLTE(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldLTE(FieldValidationRegex, v))
}

// ValidationRegexContains applies the Contains predicate on the "validation_regex" field.
func ValidationRegexContains(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContains(FieldValidationRegex, v))
}

// ValidationRegexHasPrefix applies the HasPrefix predicate on the "validation_regex" field.
func ValidationRegexHasPrefix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasPrefix(FieldValidationRegex, v))
}

// ValidationRegexHasSuffix applies the HasSuffix predicate on the "validation_regex" field.
func ValidationRegexHasSuffix(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldHasSuffix(FieldValidationRegex, v))
}

// ValidationRegexIsNil applies the IsNil predicate on the "validation_regex" field.
func ValidationRegexIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldValidationRegex))
}

// ValidationRegexNotNil applies the NotNil predicate on the "validation_regex" field.
func ValidationRegexNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldValidationRegex))
}

// ValidationRegexEqualFold applies the EqualFold predicate on the "validation_regex" field.
func ValidationRegexEqualFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldEqualFold(FieldValidationRegex, v))
}

// ValidationRegexContainsFold applies the ContainsFold predicate on the "validation_regex" field.
func ValidationRegexContainsFold(v string) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldContainsFold(FieldValidationRegex, v))
}

// OptionsIsNil applies the IsNil predicate on the "options" field.
func OptionsIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldOptions))
}

// OptionsNotNil applies the NotNil predicate on the "options" field.
func OptionsNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldOptions))
}

// RelationConfigIsNil applies the IsNil predicate on the "relation_config" field.
func RelationConfigIsNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldIsNull(FieldRelationConfig))
}

// RelationConfigNotNil applies the NotNil predicate on the "relation_config" field.
func RelationConfigNotNil() predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.FieldNotNull(FieldRelationConfig))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldDefinition) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldDefinition) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldDefinition) predicate.FieldDefinition {
	return predicate.FieldDefinition(sql.NotPredicates(p))
}
